// Hardcoded decade album lists — 8 decades × 48 albums each.
// Used by /api/admin/populate-decades to seed the decade_albums table via AM search.

const DECADE_ALBUMS = {
  '1950s': [
    { artist: 'Frank Sinatra',        title: 'In the Wee Small Hours' },
    { artist: 'Elvis Presley',        title: 'Elvis Presley' },
    { artist: 'Miles Davis',          title: 'Kind of Blue' },
    { artist: 'John Coltrane',        title: 'Blue Train' },
    { artist: 'Charles Mingus',       title: 'Mingus Ah Um' },
    { artist: 'Little Richard',       title: "Here's Little Richard" },
    { artist: 'Buddy Holly',          title: 'The "Chirping" Crickets' },
    { artist: 'Ray Charles',          title: 'The Genius of Ray Charles' },
    { artist: 'Billie Holiday',       title: 'Lady Sings the Blues' },
    { artist: 'Chet Baker',           title: 'Chet Baker Sings' },
    { artist: 'Thelonious Monk',      title: 'Brilliant Corners' },
    { artist: 'Ella Fitzgerald',      title: 'Ella Fitzgerald Sings the Cole Porter Songbook' },
    { artist: 'Nat King Cole',        title: 'Love Is the Thing' },
    { artist: 'Harry Belafonte',      title: 'Calypso' },
    { artist: 'Chuck Berry',          title: 'After School Session' },
    { artist: 'Johnny Cash',          title: 'With His Hot and Blue Guitar' },
    { artist: 'The Everly Brothers',  title: 'Songs Our Daddy Taught Us' },
    { artist: 'Elvis Presley',        title: 'Elvis' },
    { artist: 'Frank Sinatra',        title: "Songs for Swingin' Lovers!" },
    { artist: 'Dinah Washington',     title: "What a Diff'rence a Day Makes!" },
    { artist: 'Ornette Coleman',      title: 'The Shape of Jazz to Come' },
    { artist: 'Dave Brubeck',         title: 'Time Out' },
    { artist: 'Miles Davis',          title: 'Birth of the Cool' },
    { artist: 'John Coltrane',        title: 'Giant Steps' },
    { artist: 'Muddy Waters',         title: 'The Best of Muddy Waters' },
    { artist: 'Bo Diddley',           title: 'Bo Diddley' },
    { artist: 'Jerry Lee Lewis',      title: 'Jerry Lee Lewis' },
    { artist: 'Carl Perkins',         title: 'Dance Album of Carl Perkins' },
    { artist: 'Fats Domino',          title: 'This Is Fats' },
    { artist: 'Sam Cooke',            title: 'Encore' },
    { artist: 'Louis Armstrong',      title: 'Louis Armstrong Plays W.C. Handy' },
    { artist: 'Sarah Vaughan',        title: 'Sarah Vaughan with Clifford Brown' },
    { artist: 'Sonny Rollins',        title: 'Saxophone Colossus' },
    { artist: 'Art Blakey',           title: "Moanin'" },
    { artist: 'Duke Ellington',       title: 'Ellington at Newport' },
    { artist: 'Gene Vincent',         title: 'Bluejean Bop!' },
    { artist: "Howlin' Wolf",         title: "Moanin' in the Moonlight" },
    { artist: 'Hank Williams',        title: "Moanin' the Blues" },
    { artist: 'Patsy Cline',          title: 'Patsy Cline' },
    { artist: 'The Platters',         title: 'The Platters' },
    { artist: 'Johnny Cash',          title: 'Songs of Our Soil' },
    { artist: 'Charles Mingus',       title: 'Pithecanthropus Erectus' },
    { artist: 'Gerry Mulligan',       title: 'Night Lights' },
    { artist: 'Dizzy Gillespie',      title: 'Sonny Side Up' },
    { artist: 'Billie Holiday',       title: 'Lady in Satin' },
    { artist: 'Nina Simone',          title: 'Little Girl Blue' },
    { artist: 'Ahmad Jamal',          title: 'At the Pershing: But Not for Me' },
    { artist: 'The Kingston Trio',    title: 'The Kingston Trio' },
  ],
  '1960s': [
    { artist: 'The Beatles',                  title: "Sgt. Pepper's Lonely Hearts Club Band" },
    { artist: 'The Beatles',                  title: 'Revolver' },
    { artist: 'The Beatles',                  title: 'Rubber Soul' },
    { artist: 'The Beatles',                  title: 'Abbey Road' },
    { artist: 'Bob Dylan',                    title: 'Highway 61 Revisited' },
    { artist: 'Bob Dylan',                    title: 'Blonde on Blonde' },
    { artist: 'The Beach Boys',               title: 'Pet Sounds' },
    { artist: 'The Velvet Underground & Nico',title: 'The Velvet Underground & Nico' },
    { artist: 'Jimi Hendrix',                 title: 'Are You Experienced' },
    { artist: 'Jimi Hendrix',                 title: 'Electric Ladyland' },
    { artist: 'The Rolling Stones',           title: 'Let It Bleed' },
    { artist: 'The Rolling Stones',           title: 'Beggars Banquet' },
    { artist: 'The Doors',                    title: 'The Doors' },
    { artist: 'The Doors',                    title: 'Strange Days' },
    { artist: 'Aretha Franklin',              title: 'I Never Loved a Man the Way I Love You' },
    { artist: 'Aretha Franklin',              title: 'Lady Soul' },
    { artist: 'Marvin Gaye',                  title: 'In the Groove' },
    { artist: 'Nina Simone',                  title: 'Wild Is the Wind' },
    { artist: 'Simon & Garfunkel',            title: 'Bridge Over Troubled Water' },
    { artist: 'Simon & Garfunkel',            title: 'Bookends' },
    { artist: 'Led Zeppelin',                 title: 'Led Zeppelin' },
    { artist: 'Led Zeppelin',                 title: 'Led Zeppelin II' },
    { artist: 'King Crimson',                 title: 'In the Court of the Crimson King' },
    { artist: 'The Who',                      title: 'Tommy' },
    { artist: 'The Who',                      title: 'My Generation' },
    { artist: 'Love',                         title: 'Forever Changes' },
    { artist: 'Van Morrison',                 title: 'Astral Weeks' },
    { artist: 'Creedence Clearwater Revival', title: 'Green River' },
    { artist: 'Creedence Clearwater Revival', title: 'Willy and the Poor Boys' },
    { artist: 'Otis Redding',                 title: 'Otis Blue' },
    { artist: 'John Coltrane',                title: 'A Love Supreme' },
    { artist: 'Miles Davis',                  title: 'In a Silent Way' },
    { artist: 'Miles Davis',                  title: 'Bitches Brew' },
    { artist: 'The Kinks',                    title: 'The Kinks Are the Village Green Preservation Society' },
    { artist: 'Sly and the Family Stone',     title: 'Stand!' },
    { artist: 'Johnny Cash',                  title: 'At Folsom Prison' },
    { artist: 'Johnny Cash',                  title: 'At San Quentin' },
    { artist: 'The Band',                     title: 'Music from Big Pink' },
    { artist: 'The Band',                     title: 'The Band' },
    { artist: 'Dusty Springfield',            title: 'Dusty in Memphis' },
    { artist: 'Cream',                        title: 'Disraeli Gears' },
    { artist: 'Cream',                        title: 'Wheels of Fire' },
    { artist: 'Jefferson Airplane',           title: 'Surrealistic Pillow' },
    { artist: 'The Zombies',                  title: 'Odessey and Oracle' },
    { artist: 'Santana',                      title: 'Santana' },
    { artist: 'Frank Zappa',                  title: 'Hot Rats' },
    { artist: 'The Supremes',                 title: 'Where Did Our Love Go' },
    { artist: 'James Brown',                  title: 'Live at the Apollo' },
  ],
  '1970s': [
    { artist: 'Pink Floyd',         title: 'The Dark Side of the Moon' },
    { artist: 'Pink Floyd',         title: 'Wish You Were Here' },
    { artist: 'Pink Floyd',         title: 'The Wall' },
    { artist: 'Led Zeppelin',       title: 'Led Zeppelin IV' },
    { artist: 'David Bowie',        title: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars' },
    { artist: 'David Bowie',        title: 'Heroes' },
    { artist: 'Fleetwood Mac',      title: 'Rumours' },
    { artist: 'Stevie Wonder',      title: 'Songs in the Key of Life' },
    { artist: 'Stevie Wonder',      title: 'Innervisions' },
    { artist: 'Marvin Gaye',        title: "What's Going On" },
    { artist: 'Bruce Springsteen',  title: 'Born to Run' },
    { artist: 'Bruce Springsteen',  title: 'Darkness on the Edge of Town' },
    { artist: 'Eagles',             title: 'Hotel California' },
    { artist: 'Eagles',             title: 'Their Greatest Hits' },
    { artist: 'The Clash',          title: 'London Calling' },
    { artist: 'Sex Pistols',        title: 'Never Mind the Bollocks' },
    { artist: 'Ramones',            title: 'Ramones' },
    { artist: 'Black Sabbath',      title: 'Paranoid' },
    { artist: 'Black Sabbath',      title: 'Master of Reality' },
    { artist: 'AC/DC',              title: 'Highway to Hell' },
    { artist: 'AC/DC',              title: 'Back in Black' },
    { artist: 'Queen',              title: 'A Night at the Opera' },
    { artist: 'Queen',              title: 'News of the World' },
    { artist: 'Elton John',         title: 'Goodbye Yellow Brick Road' },
    { artist: 'Elton John',         title: 'Honky Château' },
    { artist: 'Joni Mitchell',      title: 'Blue' },
    { artist: 'Neil Young',         title: 'Harvest' },
    { artist: 'Bob Marley',         title: 'Exodus' },
    { artist: 'Bob Marley',         title: 'Rastaman Vibration' },
    { artist: 'Kraftwerk',          title: 'Autobahn' },
    { artist: 'Kraftwerk',          title: 'The Man-Machine' },
    { artist: 'Donna Summer',       title: 'Bad Girls' },
    { artist: 'Bee Gees',           title: 'Saturday Night Fever' },
    { artist: 'Talking Heads',      title: 'Fear of Music' },
    { artist: 'Talking Heads',      title: 'More Songs About Buildings and Food' },
    { artist: 'Television',         title: 'Marquee Moon' },
    { artist: 'Patti Smith',        title: 'Horses' },
    { artist: 'The Rolling Stones', title: 'Exile on Main St.' },
    { artist: 'Lou Reed',           title: 'Transformer' },
    { artist: 'Van Halen',          title: 'Van Halen' },
    { artist: 'Supertramp',         title: 'Breakfast in America' },
    { artist: 'The Who',            title: "Who's Next" },
    { artist: 'Parliament',         title: 'Mothership Connection' },
    { artist: 'Curtis Mayfield',    title: 'Super Fly' },
    { artist: 'Al Green',           title: "Let's Stay Together" },
    { artist: 'Joy Division',       title: 'Unknown Pleasures' },
    { artist: 'Michael Jackson',    title: 'Off the Wall' },
    { artist: 'Earth, Wind & Fire', title: "All 'N All" },
  ],
  '1980s': [
    { artist: 'Michael Jackson',   title: 'Thriller' },
    { artist: 'Michael Jackson',   title: 'Bad' },
    { artist: 'Prince',            title: 'Purple Rain' },
    { artist: 'Prince',            title: "Sign o' the Times" },
    { artist: 'Madonna',           title: 'Like a Prayer' },
    { artist: 'Madonna',           title: 'True Blue' },
    { artist: 'U2',                title: 'The Joshua Tree' },
    { artist: 'U2',                title: 'Achtung Baby' },
    { artist: 'Bruce Springsteen', title: 'Born in the U.S.A.' },
    { artist: "Guns N' Roses",     title: 'Appetite for Destruction' },
    { artist: 'Metallica',         title: 'Master of Puppets' },
    { artist: 'Metallica',         title: 'Ride the Lightning' },
    { artist: 'Slayer',            title: 'Reign in Blood' },
    { artist: 'Iron Maiden',       title: 'The Number of the Beast' },
    { artist: 'The Smiths',        title: 'The Queen Is Dead' },
    { artist: 'The Cure',          title: 'Disintegration' },
    { artist: 'Joy Division',      title: 'Closer' },
    { artist: 'New Order',         title: 'Power, Corruption & Lies' },
    { artist: 'Depeche Mode',      title: 'Violator' },
    { artist: 'Talking Heads',     title: 'Remain in Light' },
    { artist: 'Talking Heads',     title: 'Speaking in Tongues' },
    { artist: 'R.E.M.',            title: 'Murmur' },
    { artist: 'R.E.M.',            title: 'Document' },
    { artist: 'Whitney Houston',   title: 'Whitney Houston' },
    { artist: 'Janet Jackson',     title: 'Control' },
    { artist: 'Janet Jackson',     title: 'Rhythm Nation 1814' },
    { artist: 'Public Enemy',      title: 'It Takes a Nation of Millions to Hold Us Back' },
    { artist: 'N.W.A',             title: 'Straight Outta Compton' },
    { artist: 'Beastie Boys',      title: 'Licensed to Ill' },
    { artist: 'Run-D.M.C.',        title: 'Raising Hell' },
    { artist: 'Sonic Youth',       title: 'Daydream Nation' },
    { artist: 'Pixies',            title: 'Doolittle' },
    { artist: 'The Stone Roses',   title: 'The Stone Roses' },
    { artist: 'INXS',              title: 'Kick' },
    { artist: 'George Michael',    title: 'Faith' },
    { artist: 'Kate Bush',         title: 'Hounds of Love' },
    { artist: 'Tears for Fears',   title: 'Songs from the Big Chair' },
    { artist: 'Phil Collins',      title: 'No Jacket Required' },
    { artist: 'Pet Shop Boys',     title: 'Actually' },
    { artist: 'Cyndi Lauper',      title: "She's So Unusual" },
    { artist: 'Bon Jovi',          title: 'Slippery When Wet' },
    { artist: 'Def Leppard',       title: 'Hysteria' },
    { artist: 'Van Halen',         title: '1984' },
    { artist: 'Talking Heads',     title: 'Stop Making Sense' },
    { artist: 'The Police',        title: 'Synchronicity' },
    { artist: 'AC/DC',             title: 'Back in Black' },
    { artist: 'Eric B. & Rakim',   title: 'Paid in Full' },
    { artist: 'Sade',              title: 'Diamond Life' },
  ],
  '1990s': [
    { artist: 'Nirvana',                   title: 'Nevermind' },
    { artist: 'Radiohead',                 title: 'OK Computer' },
    { artist: 'Oasis',                     title: "(What's the Story) Morning Glory?" },
    { artist: 'Blur',                      title: 'Parklife' },
    { artist: 'Pearl Jam',                 title: 'Ten' },
    { artist: 'Soundgarden',               title: 'Superunknown' },
    { artist: 'Alice in Chains',           title: 'Dirt' },
    { artist: 'Red Hot Chili Peppers',     title: 'Blood Sugar Sex Magik' },
    { artist: 'Green Day',                 title: 'Dookie' },
    { artist: 'Weezer',                    title: 'Weezer' },
    { artist: 'Lauryn Hill',               title: 'The Miseducation of Lauryn Hill' },
    { artist: 'Nas',                       title: 'Illmatic' },
    { artist: 'Dr. Dre',                   title: 'The Chronic' },
    { artist: 'Tupac',                     title: 'All Eyez on Me' },
    { artist: 'The Notorious B.I.G.',      title: 'Ready to Die' },
    { artist: 'Wu-Tang Clan',              title: 'Enter the Wu-Tang (36 Chambers)' },
    { artist: 'OutKast',                   title: 'Aquemini' },
    { artist: 'A Tribe Called Quest',      title: 'The Low End Theory' },
    { artist: 'Rage Against the Machine',  title: 'Rage Against the Machine' },
    { artist: 'Massive Attack',            title: 'Mezzanine' },
    { artist: 'Portishead',                title: 'Dummy' },
    { artist: 'Björk',                     title: 'Homogenic' },
    { artist: 'Björk',                     title: 'Post' },
    { artist: 'Aphex Twin',                title: 'Richard D. James Album' },
    { artist: 'Daft Punk',                 title: 'Homework' },
    { artist: 'The Prodigy',               title: 'The Fat of the Land' },
    { artist: 'My Bloody Valentine',       title: 'Loveless' },
    { artist: 'Pavement',                  title: 'Slanted and Enchanted' },
    { artist: 'Elliott Smith',             title: 'Either/Or' },
    { artist: 'Jeff Buckley',              title: 'Grace' },
    { artist: 'Fiona Apple',               title: 'Tidal' },
    { artist: 'Smashing Pumpkins',         title: 'Siamese Dream' },
    { artist: 'Tool',                      title: 'Ænima' },
    { artist: 'Korn',                      title: 'Follow the Leader' },
    { artist: 'Deftones',                  title: 'Around the Fur' },
    { artist: 'Nine Inch Nails',           title: 'The Downward Spiral' },
    { artist: 'Snoop Dogg',                title: 'Doggystyle' },
    { artist: 'Jay-Z',                     title: 'Reasonable Doubt' },
    { artist: 'Missy Elliott',             title: 'Supa Dupa Fly' },
    { artist: 'TLC',                       title: 'CrazySexyCool' },
    { artist: 'Alanis Morissette',         title: 'Jagged Little Pill' },
    { artist: 'Britney Spears',            title: '...Baby One More Time' },
    { artist: 'Backstreet Boys',           title: 'Millennium' },
    { artist: 'Eminem',                    title: 'The Slim Shady LP' },
    { artist: 'Beck',                      title: 'Odelay' },
    { artist: 'Modest Mouse',              title: 'The Lonesome Crowded West' },
    { artist: 'Neutral Milk Hotel',        title: 'In the Aeroplane Over the Sea' },
    { artist: 'Buena Vista Social Club',   title: 'Buena Vista Social Club' },
  ],
  '2000s': [
    { artist: 'Kanye West',            title: 'The College Dropout' },
    { artist: 'Kanye West',            title: 'Graduation' },
    { artist: 'Eminem',                title: 'The Marshall Mathers LP' },
    { artist: 'Jay-Z',                 title: 'The Blueprint' },
    { artist: 'OutKast',               title: 'Stankonia' },
    { artist: 'MF DOOM',               title: 'Madvillainy' },
    { artist: '50 Cent',               title: "Get Rich or Die Tryin'" },
    { artist: 'Lil Wayne',             title: 'Tha Carter III' },
    { artist: 'Radiohead',             title: 'Kid A' },
    { artist: 'Radiohead',             title: 'In Rainbows' },
    { artist: 'Arctic Monkeys',        title: "Whatever People Say I Am, That's What I'm Not" },
    { artist: 'The Strokes',           title: 'Is This It' },
    { artist: 'Interpol',              title: 'Turn on the Bright Lights' },
    { artist: 'The White Stripes',     title: 'Elephant' },
    { artist: 'Franz Ferdinand',       title: 'Franz Ferdinand' },
    { artist: 'Coldplay',              title: 'A Rush of Blood to the Head' },
    { artist: 'Coldplay',              title: 'Viva la Vida' },
    { artist: 'Amy Winehouse',         title: 'Back to Black' },
    { artist: 'Beyoncé',               title: "B'Day" },
    { artist: 'Beyoncé',               title: 'I Am… Sasha Fierce' },
    { artist: 'Justin Timberlake',     title: 'FutureSex/LoveSounds' },
    { artist: 'Rihanna',               title: 'Good Girl Gone Bad' },
    { artist: 'Lady Gaga',             title: 'The Fame' },
    { artist: 'Britney Spears',        title: 'Blackout' },
    { artist: 'Daft Punk',             title: 'Discovery' },
    { artist: 'The Killers',           title: 'Hot Fuss' },
    { artist: 'Arcade Fire',           title: 'Funeral' },
    { artist: 'Sufjan Stevens',        title: 'Illinois' },
    { artist: 'Bon Iver',              title: 'For Emma, Forever Ago' },
    { artist: 'Fleet Foxes',           title: 'Fleet Foxes' },
    { artist: 'LCD Soundsystem',       title: 'Sound of Silver' },
    { artist: 'Animal Collective',     title: 'Merriweather Post Pavilion' },
    { artist: 'Gorillaz',              title: 'Demon Days' },
    { artist: 'Linkin Park',           title: 'Hybrid Theory' },
    { artist: 'System of a Down',      title: 'Toxicity' },
    { artist: 'Green Day',             title: 'American Idiot' },
    { artist: 'My Chemical Romance',   title: 'The Black Parade' },
    { artist: 'Paramore',              title: 'Riot!' },
    { artist: 'Blink-182',             title: 'Blink-182' },
    { artist: 'Fall Out Boy',          title: 'From Under the Cork Tree' },
    { artist: 'The xx',                title: 'xx' },
    { artist: 'Joanna Newsom',         title: 'Ys' },
    { artist: 'Burial',                title: 'Untrue' },
    { artist: 'M.I.A.',                title: 'Kala' },
    { artist: 'Vampire Weekend',       title: 'Vampire Weekend' },
    { artist: 'Phoenix',               title: 'Wolfgang Amadeus Phoenix' },
    { artist: 'Justice',               title: 'Cross' },
    { artist: 'Alicia Keys',           title: 'Songs in A Minor' },
  ],
  '2010s': [
    { artist: 'Kendrick Lamar',     title: 'To Pimp a Butterfly' },
    { artist: 'Kendrick Lamar',     title: 'good kid, m.A.A.d city' },
    { artist: 'Kanye West',         title: 'My Beautiful Dark Twisted Fantasy' },
    { artist: 'Drake',              title: 'Take Care' },
    { artist: 'Travis Scott',       title: 'Astroworld' },
    { artist: 'Future',             title: 'DS2' },
    { artist: 'Tyler, The Creator', title: 'Igor' },
    { artist: 'Frank Ocean',        title: 'Blonde' },
    { artist: 'Frank Ocean',        title: 'channel ORANGE' },
    { artist: 'Beyoncé',            title: 'Lemonade' },
    { artist: 'Beyoncé',            title: 'Beyoncé' },
    { artist: 'Taylor Swift',       title: '1989' },
    { artist: 'Taylor Swift',       title: 'Red' },
    { artist: 'Ariana Grande',      title: 'Thank U, Next' },
    { artist: 'Billie Eilish',      title: 'When We All Fall Asleep, Where Do We Go?' },
    { artist: 'Lorde',              title: 'Melodrama' },
    { artist: 'Lana Del Rey',       title: 'Norman Fucking Rockwell!' },
    { artist: 'The Weeknd',         title: 'House of Balloons' },
    { artist: 'The Weeknd',         title: 'Beauty Behind the Madness' },
    { artist: 'SZA',                title: 'Ctrl' },
    { artist: 'Rihanna',            title: 'Anti' },
    { artist: 'Solange',            title: 'A Seat at the Table' },
    { artist: 'Tame Impala',        title: 'Currents' },
    { artist: 'Tame Impala',        title: 'Lonerism' },
    { artist: 'Arctic Monkeys',     title: 'AM' },
    { artist: 'XXXTENTACION',       title: '?' },
    { artist: 'Bon Iver',           title: 'Bon Iver, Bon Iver' },
    { artist: 'Sufjan Stevens',     title: 'Carrie & Lowell' },
    { artist: 'Phoebe Bridgers',    title: 'Stranger in the Alps' },
    { artist: 'Vampire Weekend',    title: 'Modern Vampires of the City' },
    { artist: 'LCD Soundsystem',    title: 'This Is Happening' },
    { artist: 'Daft Punk',          title: 'Random Access Memories' },
    { artist: 'Charli XCX',         title: 'Pop 2' },
    { artist: 'Carly Rae Jepsen',   title: 'Emotion' },
    { artist: 'Tyler, The Creator', title: 'Flower Boy' },
    { artist: 'Playboi Carti',      title: 'Die Lit' },
    { artist: 'Young Thug',         title: 'Barter 6' },
    { artist: 'A$AP Rocky',         title: 'At.Long.Last.A$AP' },
    { artist: 'J. Cole',            title: '2014 Forest Hills Drive' },
    { artist: 'Mac Miller',         title: 'Swimming' },
    { artist: 'Chance the Rapper',  title: 'Acid Rap' },
    { artist: 'Childish Gambino',   title: 'Awaken, My Love!' },
    { artist: 'FKA twigs',          title: 'LP1' },
    { artist: 'Beach House',        title: 'Bloom' },
    { artist: 'Grimes',             title: 'Art Angels' },
    { artist: 'Death Grips',        title: 'The Money Store' },
    { artist: 'Brockhampton',       title: 'Saturation' },
    { artist: 'Mitski',             title: 'Be the Cowboy' },
  ],
  '2020s': [
    { artist: 'Taylor Swift',         title: 'Midnights' },
    { artist: 'Taylor Swift',         title: 'The Tortured Poets Department' },
    { artist: 'Olivia Rodrigo',       title: 'Sour' },
    { artist: 'Olivia Rodrigo',       title: 'Guts' },
    { artist: 'Billie Eilish',        title: 'Hit Me Hard and Soft' },
    { artist: 'SZA',                  title: 'SOS' },
    { artist: 'Sabrina Carpenter',    title: "Short n' Sweet" },
    { artist: 'Charli XCX',           title: 'BRAT' },
    { artist: 'Beyoncé',              title: 'Cowboy Carter' },
    { artist: 'Beyoncé',              title: 'Renaissance' },
    { artist: 'The Weeknd',           title: 'After Hours' },
    { artist: 'Dua Lipa',             title: 'Future Nostalgia' },
    { artist: 'Ariana Grande',        title: 'Eternal Sunshine' },
    { artist: 'Bad Bunny',            title: 'Un Verano Sin Ti' },
    { artist: 'Bad Bunny',            title: 'Nadie Sabe Lo Que Va a Pasar Mañana' },
    { artist: 'Travis Scott',         title: 'Utopia' },
    { artist: 'Drake',                title: 'For All the Dogs' },
    { artist: 'Metro Boomin',         title: 'Heroes & Villains' },
    { artist: 'Future & Metro Boomin',title: "We Don't Trust You" },
    { artist: 'Tyler, The Creator',   title: 'Call Me If You Get Lost' },
    { artist: 'Playboi Carti',        title: 'Whole Lotta Red' },
    { artist: 'Kendrick Lamar',       title: 'Mr. Morale & the Big Steppers' },
    { artist: 'J. Cole',              title: 'The Off-Season' },
    { artist: 'Gunna',                title: 'A Gift & a Curse' },
    { artist: 'Fred again..',         title: 'Actual Life 3' },
    { artist: 'Skrillex',             title: 'Quest for Fire' },
    { artist: 'Lana Del Rey',         title: "Did You Know That There's a Tunnel Under Ocean Blvd" },
    { artist: 'Boygenius',            title: 'The Record' },
    { artist: 'Mitski',               title: 'The Land Is Inhospitable and So Are We' },
    { artist: 'Big Thief',            title: 'Dragon New Warm Mountain I Believe in You' },
    { artist: 'Phoebe Bridgers',      title: 'Punisher' },
    { artist: 'Noah Kahan',           title: 'Stick Season' },
    { artist: 'Zach Bryan',           title: 'Zach Bryan' },
    { artist: 'Morgan Wallen',        title: 'One Thing at a Time' },
    { artist: 'Burna Boy',            title: 'I Told Them…' },
    { artist: 'Rema',                 title: 'Rave & Roses' },
    { artist: 'Asake',                title: 'Work of Art' },
    { artist: 'Tems',                 title: 'Born in the Wild' },
    { artist: 'Karol G',              title: 'Mañana Será Bonito' },
    { artist: 'Feid',                 title: 'Ferxxocalipsis' },
    { artist: 'Rauw Alejandro',       title: 'Saturno' },
    { artist: 'Rosalía',              title: 'Motomami' },
    { artist: 'Ice Spice',            title: 'Like..?' },
    { artist: 'Lil Yachty',           title: "Let's Start Here" },
    { artist: 'Caroline Polachek',    title: 'Desire, I Want to Turn Into You' },
    { artist: 'Sampha',               title: 'Lahai' },
    { artist: 'Faye Webster',         title: 'Underdressed at the Symphony' },
    { artist: 'Adrianne Lenker',      title: 'Bright Future' },
  ],
};

module.exports = { DECADE_ALBUMS };
