// Metadata for all 8 featured playlists (including all-time-classics which uses CLASSIC_IDS in index.js)
const FEATURED_PLAYLIST_META = [
  { id: 'all-time-classics', name: 'All-Time Classics', emoji: '🎵', description: 'The albums that changed everything. Start here.' },
  { id: 'late-night',        name: 'Late Night',        emoji: '🌙', description: 'For when the world goes quiet and the music hits different.' },
  { id: 'summer',            name: 'Summer',            emoji: '☀️', description: 'Windows down, volume up. The soundtrack to your best days.' },
  { id: 'heartbreak',        name: 'Heartbreak',        emoji: '💔', description: 'Albums that understand what you\'re going through.' },
  { id: 'road-trip',         name: 'Road Trip',         emoji: '🚗', description: 'Miles ahead, nothing behind. Let\'s drive.' },
  { id: 'chill',             name: 'Chill',             emoji: '😎', description: 'Low stakes, high comfort. Perfect background for anything.' },
  { id: 'hidden-gems',       name: 'Hidden Gems',       emoji: '🔥', description: 'The albums that flew under the radar. Your new favourites.' },
  { id: 'essentials',        name: 'Essentials',        emoji: '📚', description: 'Every music lover should hear these at least once.' },
];

// Album lists for the 7 non-classics playlists (all-time-classics uses CLASSIC_IDS in index.js)
const PLAYLIST_ALBUMS = {
  'late-night': [
    { artist: 'Frank Ocean',          title: 'Blonde' },
    { artist: 'The Blue Nile',         title: 'Hats' },
    { artist: 'Portishead',            title: 'Dummy' },
    { artist: 'Cigarettes After Sex',  title: 'Cigarettes After Sex' },
    { artist: 'Burial',                title: 'Untrue' },
    { artist: 'Miles Davis',           title: 'Kind of Blue' },
    { artist: 'The Weeknd',            title: 'Trilogy' },
    { artist: 'Mazzy Star',            title: 'Among My Swan' },
    { artist: 'Joni Mitchell',         title: 'Blue' },
    { artist: 'James Blake',           title: 'Overgrown' },
    { artist: "D'Angelo",              title: 'Voodoo' },
    { artist: 'Beach House',           title: 'Depression Cherry' },
    { artist: 'Bon Iver',              title: 'For Emma, Forever Ago' },
    { artist: 'Sade',                  title: 'Love Deluxe' },
    { artist: 'Arctic Monkeys',        title: 'AM' },
    { artist: 'Nujabes',               title: 'Modal Soul' },
    { artist: 'Chet Baker',            title: 'Chet Baker Sings' },
    { artist: 'Lana Del Rey',          title: 'Ultraviolence' },
    { artist: 'Massive Attack',        title: 'Mezzanine' },
    { artist: 'Radiohead',             title: 'Kid A' },
    { artist: 'The xx',                title: 'xx' },
    { artist: 'Zero 7',                title: 'Simple Things' },
    { artist: 'Slowdive',              title: 'Souvlaki' },
    { artist: 'Flying Lotus',          title: 'Cosmogramma' },
    { artist: 'Solange',               title: 'When I Get Home' },
    { artist: 'Cocteau Twins',         title: 'Heaven or Las Vegas' },
    { artist: 'Aphex Twin',            title: 'Selected Ambient Works 85-92' },
    { artist: 'Tom Waits',             title: 'Closing Time' },
    { artist: 'Blood Orange',          title: 'Cupid Deluxe' },
    { artist: 'Erykah Badu',           title: 'Baduizm' },
    { artist: 'Nick Drake',            title: 'Pink Moon' },
    { artist: 'Low',                   title: 'I Could Live in Hope' },
    { artist: 'Tirzah',                title: 'Devotion' },
    { artist: 'The National',          title: 'Boxer' },
    { artist: 'Daniel Caesar',         title: 'Freudian' },
    { artist: 'Talk Talk',             title: 'Laughing Stock' },
    { artist: 'Pink Floyd',            title: 'Wish You Were Here' },
    { artist: 'Bill Evans Trio',       title: 'Sunday at the Village Vanguard' },
    { artist: 'SZA',                   title: 'Ctrl' },
    { artist: 'Julee Cruise',          title: 'Floating into the Night' },
    { artist: 'Air',                   title: 'Moon Safari' },
    { artist: 'Rhye',                  title: 'Woman' },
    { artist: 'Aaliyah',               title: 'One in a Million' },
    { artist: 'Lonnie Liston Smith',   title: 'Visions of a New World' },
    { artist: 'Grouper',               title: 'Dragging a Dead Deer Up a Hill' },
    { artist: 'Songs: Ohia',           title: 'The Magnolia Electric Co.' },
    { artist: 'Maxwell',               title: "Maxwell's Urban Hang Suite" },
    { artist: 'Norah Jones',           title: 'Come Away with Me' },
  ],

  'summer': [
    { artist: 'The Beach Boys',            title: 'Pet Sounds' },
    { artist: 'Kanye West',                title: 'Graduation' },
    { artist: 'Calvin Harris',             title: 'Funk Wav Bounces Vol. 1' },
    { artist: 'Bob Marley & The Wailers',  title: 'Exodus' },
    { artist: 'Vampire Weekend',           title: 'Father of the Bride' },
    { artist: 'Kaytranada',                title: '99.9%' },
    { artist: 'Anderson .Paak',            title: 'Malibu' },
    { artist: 'Tame Impala',               title: 'Lonerism' },
    { artist: 'Lorde',                     title: 'Solar Power' },
    { artist: 'Red Hot Chili Peppers',     title: 'Californication' },
    { artist: 'Daft Punk',                 title: 'Discovery' },
    { artist: 'Khruangbin',                title: 'The Universe Smiles Upon You' },
    { artist: 'Astrud Gilberto',           title: 'The Shadow of Your Smile' },
    { artist: 'Best Coast',                title: 'Crazy for You' },
    { artist: 'Chance the Rapper',         title: 'Acid Rap' },
    { artist: 'Phoenix',                   title: 'Wolfgang Amadeus Phoenix' },
    { artist: 'Gorillaz',                  title: 'Plastic Beach' },
    { artist: 'Cut Copy',                  title: 'In Ghost Colours' },
    { artist: 'Childish Gambino',          title: 'Kauai' },
    { artist: 'Manu Chao',                 title: 'Clandestino' },
    { artist: 'Jack Johnson',              title: 'In Between Dreams' },
    { artist: 'The Internet',              title: 'Ego Death' },
    { artist: 'Bad Bunny',                 title: 'Un Verano Sin Ti' },
    { artist: 'Jorge Ben Jor',             title: 'Africa Brasil' },
    { artist: 'Friendly Fires',            title: 'Friendly Fires' },
    { artist: 'Empire of the Sun',         title: 'Walking on a Dream' },
    { artist: 'Justice',                   title: 'Cross' },
    { artist: 'Glass Animals',             title: 'How to Be a Human Being' },
    { artist: 'Stereolab',                 title: 'Dots and Loops' },
    { artist: 'MGMT',                      title: 'Oracular Spectacular' },
    { artist: 'Mac DeMarco',               title: 'Salad Days' },
    { artist: 'Burna Boy',                 title: 'African Giant' },
    { artist: 'Wizkid',                    title: 'Made in Lagos' },
    { artist: 'Real Estate',               title: 'Days' },
    { artist: 'The Avalanches',            title: 'Since I Left You' },
    { artist: 'Tyler the Creator',         title: 'Call Me If You Get Lost' },
    { artist: 'Disclosure',                title: 'Settle' },
    { artist: 'Bananarama',                title: 'Deep Sea Skiving' },
    { artist: 'Santana',                   title: 'Abraxas' },
    { artist: 'Unknown Mortal Orchestra',  title: 'Multi-Love' },
    { artist: 'Poolside',                  title: 'Pacific Standard Time' },
    { artist: 'Thundercat',                title: 'It Is What It Is' },
    { artist: 'Buena Vista Social Club',   title: 'Buena Vista Social Club' },
    { artist: 'Saint Etienne',             title: 'Foxbase Alpha' },
    { artist: 'Washed Out',                title: 'Within and Without' },
    { artist: 'Miley Cyrus',               title: 'Endless Summer Vacation' },
    { artist: 'Borns',                     title: 'Dopamine' },
    { artist: 'Sugar Ray',                 title: 'Floored' },
  ],

  'heartbreak': [
    { artist: 'Amy Winehouse',      title: 'Back to Black' },
    { artist: 'Adele',              title: '21' },
    { artist: 'Fleetwood Mac',      title: 'Rumours' },
    { artist: 'The Smiths',         title: 'The Queen Is Dead' },
    { artist: 'Lauryn Hill',        title: 'The Miseducation of Lauryn Hill' },
    { artist: 'Joy Division',       title: 'Unknown Pleasures' },
    { artist: 'Elliott Smith',      title: 'Either/Or' },
    { artist: 'Fiona Apple',        title: 'Tidal' },
    { artist: 'Beck',               title: 'Sea Change' },
    { artist: 'Marvin Gaye',        title: 'Here, My Dear' },
    { artist: 'Lykke Li',           title: 'I Never Learn' },
    { artist: 'Bon Iver',           title: 'For Emma, Forever Ago' },
    { artist: 'Bob Dylan',          title: 'Blood on the Tracks' },
    { artist: 'Sam Smith',          title: 'In the Lonely Hour' },
    { artist: 'Billie Holiday',     title: 'Lady in Satin' },
    { artist: 'Olivia Rodrigo',     title: 'SOUR' },
    { artist: 'Joji',               title: 'BALLADS 1' },
    { artist: 'Phoebe Bridgers',    title: 'Stranger in the Alps' },
    { artist: 'Usher',              title: 'Confessions' },
    { artist: 'Mary J. Blige',      title: 'My Life' },
    { artist: 'Taylor Swift',       title: 'Red (Taylor\'s Version)' },
    { artist: 'The Cure',           title: 'Disintegration' },
    { artist: 'Bon Iver',           title: '22, A Million' },
    { artist: 'Bjork',              title: 'Vulnicura' },
    { artist: 'Mount Eerie',        title: 'A Crow Looked At Me' },
    { artist: 'Julia Jacklin',      title: 'Crushing' },
    { artist: 'Sharon Van Etten',   title: 'Are We There' },
    { artist: 'Sufjan Stevens',     title: 'Carrie & Lowell' },
    { artist: 'Cat Power',          title: 'Moon Pix' },
    { artist: 'James Blake',        title: 'James Blake' },
    { artist: 'Giveon',             title: 'When It\'s All Said and Done' },
    { artist: 'Kehlani',            title: 'You Should Be Here' },
    { artist: 'Tracy Chapman',      title: 'Tracy Chapman' },
    { artist: 'Coldplay',           title: 'Ghost Stories' },
    { artist: 'Lord Huron',         title: 'Strange Trails' },
    { artist: 'Whitney Houston',    title: "I'm Your Baby Tonight" },
    { artist: 'Toni Braxton',       title: 'Toni Braxton' },
    { artist: "Sinead O'Connor",    title: 'I Do Not Want What I Haven\'t Got' },
    { artist: 'Hole',               title: 'Live Through This' },
    { artist: 'Radiohead',          title: 'A Moon Shaped Pool' },
    { artist: 'Julien Baker',       title: 'Sprained Ankle' },
    { artist: 'Angel Olsen',        title: 'Burn Your Fire for No Witness' },
    { artist: 'Mitski',             title: 'Bury Me at Makeout Creek' },
    { artist: 'Leonard Cohen',      title: 'Songs of Love and Hate' },
    { artist: 'Aretha Franklin',    title: 'I Never Loved a Man the Way I Love You' },
    { artist: 'The Antlers',        title: 'Hospice' },
    { artist: 'Kacey Musgraves',    title: 'Star-Crossed' },
    { artist: 'Lucinda Williams',   title: 'Car Wheels on a Gravel Road' },
  ],

  'road-trip': [
    { artist: 'Bruce Springsteen',            title: 'Born to Run' },
    { artist: 'The War on Drugs',             title: 'A Deeper Understanding' },
    { artist: 'Tom Petty',                    title: 'Full Moon Fever' },
    { artist: 'Arcade Fire',                  title: 'The Suburbs' },
    { artist: 'Fleet Foxes',                  title: 'Helplessness Blues' },
    { artist: 'Creedence Clearwater Revival', title: "Cosmo's Factory" },
    { artist: 'Simon & Garfunkel',            title: 'Bridge Over Troubled Water' },
    { artist: 'The Killers',                  title: 'Hot Fuss' },
    { artist: 'Modest Mouse',                 title: 'The Lonesome Crowded West' },
    { artist: 'Lorde',                        title: 'Melodrama' },
    { artist: 'Talking Heads',                title: 'Remain in Light' },
    { artist: 'OutKast',                      title: 'Stankonia' },
    { artist: 'Vampire Weekend',              title: 'Modern Vampires of the City' },
    { artist: 'Haim',                         title: 'Days Are Gone' },
    { artist: 'U2',                           title: 'The Joshua Tree' },
    { artist: 'R.E.M.',                       title: 'Automatic for the People' },
    { artist: 'Daft Punk',                    title: 'Random Access Memories' },
    { artist: 'Eagles',                       title: 'Hotel California' },
    { artist: 'Paul Simon',                   title: 'Graceland' },
    { artist: 'Dire Straits',                 title: 'Brothers in Arms' },
    { artist: 'The Strokes',                  title: 'Is This It' },
    { artist: 'The Doors',                    title: 'L.A. Woman' },
    { artist: 'Kings of Leon',                title: 'Only by the Night' },
    { artist: 'Steely Dan',                   title: 'Aja' },
    { artist: 'Tracy Chapman',                title: 'New Beginning' },
    { artist: 'Led Zeppelin',                 title: 'Led Zeppelin IV' },
    { artist: 'Maggie Rogers',                title: 'Heard It In A Past Life' },
    { artist: 'Leon Bridges',                 title: 'Coming Home' },
    { artist: 'Future Islands',               title: 'Singles' },
    { artist: 'MIA',                          title: 'Kala' },
    { artist: 'Beastie Boys',                 title: "Paul's Boutique" },
    { artist: 'Duran Duran',                  title: 'Rio' },
    { artist: 'The Doobie Brothers',          title: 'Minute by Minute' },
    { artist: 'Oasis',                        title: "(What's the Story) Morning Glory?" },
    { artist: 'The Allman Brothers Band',     title: 'Eat a Peach' },
    { artist: 'A Tribe Called Quest',         title: 'The Low End Theory' },
    { artist: 'Sheryl Crow',                  title: 'Tuesday Night Music Club' },
    { artist: 'Wilco',                        title: 'Yankee Hotel Foxtrot' },
    { artist: 'The Cars',                     title: 'The Cars' },
    { artist: 'Chromeo',                      title: 'Fancy Footwork' },
    { artist: 'Big Thief',                    title: 'Dragon New Warm Mountain I Believe in You' },
    { artist: "The Go-Go's",                  title: 'Beauty and the Beat' },
    { artist: 'Kansas',                       title: 'Leftoverture' },
    { artist: 'The 1975',                     title: 'Notes on a Conditional Form' },
    { artist: 'Japanese Breakfast',           title: 'Jubilee' },
    { artist: 'Janelle Monae',                title: 'The ArchAndroid' },
    { artist: 'Hall & Oates',                 title: 'Voices' },
    { artist: 'Alabama Shakes',               title: 'Sound & Color' },
  ],

  'chill': [
    { artist: 'Zero 7',                         title: 'When It Falls' },
    { artist: 'Khruangbin & Leon Bridges',       title: 'Texas Sun' },
    { artist: 'Saba',                            title: 'Care For Me' },
    { artist: 'Men I Trust',                     title: 'Oncle Jazz' },
    { artist: 'Thievery Corporation',            title: 'The Richest Man in Babylon' },
    { artist: 'SZA',                             title: 'SOS' },
    { artist: 'Groove Armada',                   title: 'Goodbye Country (Hello Nightclub)' },
    { artist: 'J Dilla',                         title: 'Donuts' },
    { artist: 'BADBADNOTGOOD',                   title: 'IV' },
    { artist: 'Bill Withers',                    title: 'Still Bill' },
    { artist: 'Benny Sings',                     title: 'Music' },
    { artist: 'Tom Misch',                       title: 'Geography' },
    { artist: 'Clairo',                          title: 'Immunity' },
    { artist: 'Yussef Kamaal',                   title: 'Black Focus' },
    { artist: 'Snoh Aalegra',                    title: 'Ugh, those feels again' },
    { artist: 'Mac Miller',                      title: 'Swimming' },
    { artist: 'Bibio',                           title: 'Ambivalence Avenue' },
    { artist: 'Masego',                          title: 'Lady Lady' },
    { artist: 'FKJ',                             title: 'French Kiwi Juice' },
    { artist: 'Toro y Moi',                      title: 'Anything in Return' },
    { artist: 'Moonchild',                       title: 'Voyager' },
    { artist: 'Corinne Bailey Rae',              title: 'Corinne Bailey Rae' },
    { artist: 'Norah Jones',                     title: 'Feels Like Home' },
    { artist: 'Hiatus Kaiyote',                  title: 'Choose Your Weapon' },
    { artist: 'The Whitest Boy Alive',           title: 'Dreams' },
    { artist: 'Jordan Rakei',                    title: 'Wallflower' },
    { artist: 'Ravyn Lenae',                     title: 'HYPNOS' },
    { artist: 'Little Dragon',                   title: 'Ritual Union' },
    { artist: 'Unknown Mortal Orchestra',        title: 'II' },
    { artist: 'Kindness',                        title: 'Otherness' },
    { artist: 'Connan Mockasin',                 title: 'Forever Dolphin Love' },
    { artist: 'Dijon',                           title: 'Absolutely' },
    { artist: 'Blood Orange',                    title: 'Negro Swan' },
    { artist: 'Shuggie Otis',                    title: 'Inspiration Information' },
    { artist: 'Bobby Hutcherson',                title: 'Montara' },
    { artist: 'Bonobo',                          title: 'Black Sands' },
    { artist: 'Lianne La Havas',                 title: 'Lianne La Havas' },
    { artist: 'Homeshake',                       title: 'Midnight Snack' },
    { artist: 'Pino Palladino & Blake Mills',    title: 'Notes with Attachments' },
    { artist: 'Summer Walker',                   title: 'Over It' },
    { artist: 'Free Nationals',                  title: 'Free Nationals' },
    { artist: 'Noname',                          title: 'Telefone' },
    { artist: 'Nao',                             title: 'For All We Know' },
    { artist: 'Moses Sumney',                    title: 'grae' },
    { artist: 'Kadhja Bonet',                    title: 'The Visitor' },
    { artist: 'Alice Coltrane',                  title: 'Journey in Satchidananda' },
    { artist: 'Goldfrapp',                       title: 'Seventh Tree' },
    { artist: 'Morcheeba',                       title: 'Big Calm' },
  ],

  'hidden-gems': [
    { artist: 'The Avalanches',                    title: 'Wildflower' },
    { artist: "L'Imperatrice",                     title: 'Matahari' },
    { artist: 'Fishmans',                          title: 'Long Season' },
    { artist: 'Spellling',                         title: 'The Turning Wheel' },
    { artist: 'Injury Reserve',                    title: 'By the Time I Get to Venus' },
    { artist: 'Genesis Owusu',                     title: 'Smiling with No Teeth' },
    { artist: 'Weyes Blood',                       title: 'Titanic Rising' },
    { artist: 'Sudan Archives',                    title: 'Natural Brown Prom Queen' },
    { artist: 'Yves Tumor',                        title: 'Heaven to a Tortured Mind' },
    { artist: "The Maria's",                       title: 'Cinema' },
    { artist: 'Giles Giles and Fripp',             title: 'The Cheerful Insanity of Giles Giles and Fripp' },
    { artist: 'Mort Garson',                       title: 'Plantasia' },
    { artist: 'Sweet Trip',                        title: 'Velocity: Design: Comfort' },
    { artist: 'Prefab Sprout',                     title: 'Steve McQueen' },
    { artist: 'Arthur Russell',                    title: 'World of Echo' },
    { artist: 'Linda Perhacs',                     title: 'Parallelograms' },
    { artist: 'Broadcast',                         title: 'Tender Buttons' },
    { artist: 'The Sound',                         title: 'Jeopardy' },
    { artist: 'Betty Davis',                       title: 'Betty Davis' },
    { artist: 'Nu Genea',                          title: 'Bar Mediterraneo' },
    { artist: 'Altin Gun',                         title: 'Gece' },
    { artist: 'Kikagaku Moyo',                     title: 'Masana Temples' },
    { artist: 'Ichiko Aoba',                       title: 'Windswept Adan' },
    { artist: 'black midi',                        title: 'Hellfire' },
    { artist: 'Dry Cleaning',                      title: 'New Long Leg' },
    { artist: 'Wednesday',                         title: 'Rat Saw God' },
    { artist: 'Pescado Rabioso',                   title: 'Artaud' },
    { artist: 'Jorge Ben',                         title: 'A Tabua De Esmeralda' },
    { artist: 'Nala Sinephro',                     title: 'Space 1.8' },
    { artist: 'Floating Points & Pharoah Sanders', title: 'Promises' },
    { artist: 'Haruomi Hosono',                    title: 'Pacific' },
    { artist: 'Tatsuro Yamashita',                 title: 'For You' },
    { artist: 'Cassandra Jenkins',                 title: 'An Overview on Phenomenal Nature' },
    { artist: 'Nilufer Yanya',                     title: 'PAINLESS' },
    { artist: 'The Beths',                         title: 'Expert in a Dying Field' },
    { artist: 'Jockstrap',                         title: 'I Love You Jennifer B' },
    { artist: 'Caroline Polachek',                 title: 'Desire, I Want To Turn Into You' },
    { artist: 'Barrie',                            title: 'Barbara' },
    { artist: 'Lous and the Yakuza',               title: 'Gore' },
    { artist: 'Pa Salieu',                         title: 'Send Them to Coventry' },
    { artist: 'Little Simz',                       title: 'Sometimes I Might Be Introvert' },
    { artist: 'The Comet Is Coming',               title: 'Trust in the Lifeforce of the Deep Mystery' },
    { artist: 'SAULT',                             title: 'Untitled (Black Is)' },
    { artist: 'Kero Kero Bonito',                  title: "Time 'n' Place" },
    { artist: 'US Girls',                          title: 'In a Poem Unlimited' },
    { artist: 'Mdou Moctar',                       title: 'Afrique Victime' },
    { artist: 'Viagra Boys',                       title: 'Cave World' },
    { artist: 'Chat Pile',                         title: "God's Country" },
  ],

  'essentials': [
    { artist: 'The Beatles',                  title: 'Abbey Road' },
    { artist: 'Pink Floyd',                   title: 'The Dark Side of the Moon' },
    { artist: 'Kendrick Lamar',               title: 'To Pimp a Butterfly' },
    { artist: 'Marvin Gaye',                  title: "What's Going On" },
    { artist: 'Radiohead',                    title: 'OK Computer' },
    { artist: 'Michael Jackson',              title: 'Thriller' },
    { artist: 'Nirvana',                      title: 'Nevermind' },
    { artist: 'Stevie Wonder',                title: 'Songs in the Key of Life' },
    { artist: 'Prince',                       title: 'Purple Rain' },
    { artist: 'The Velvet Underground & Nico', title: 'The Velvet Underground & Nico' },
    { artist: 'David Bowie',                  title: 'The Rise and Fall of Ziggy Stardust' },
    { artist: 'Aretha Franklin',              title: 'Lady Soul' },
    { artist: 'Bob Dylan',                    title: 'Highway 61 Revisited' },
    { artist: 'The Jimi Hendrix Experience',  title: 'Are You Experienced' },
    { artist: 'Amy Winehouse',                title: 'Back to Black' },
    { artist: 'Lauryn Hill',                  title: 'The Miseducation of Lauryn Hill' },
    { artist: 'Nas',                          title: 'Illmatic' },
    { artist: 'Public Enemy',                 title: 'It Takes a Nation of Millions to Hold Us Back' },
    { artist: 'Led Zeppelin',                 title: 'Led Zeppelin II' },
    { artist: 'Madonna',                      title: 'Like a Prayer' },
    { artist: 'Neutral Milk Hotel',           title: 'In the Aeroplane Over the Sea' },
    { artist: 'Bjork',                        title: 'Homogenic' },
    { artist: 'OutKast',                      title: 'Aquemini' },
    { artist: 'Joy Division',                 title: 'Closer' },
    { artist: 'The Clash',                    title: 'London Calling' },
    { artist: 'Patti Smith',                  title: 'Horses' },
    { artist: 'Talking Heads',                title: 'Stop Making Sense' },
    { artist: 'Wu-Tang Clan',                 title: 'Enter the Wu-Tang (36 Chambers)' },
    { artist: 'Portishead',                   title: 'Dummy' },
    { artist: 'Arcade Fire',                  title: 'Funeral' },
    { artist: 'Kanye West',                   title: 'My Beautiful Dark Twisted Fantasy' },
    { artist: 'Frank Ocean',                  title: 'Channel Orange' },
    { artist: 'Daft Punk',                    title: 'Homework' },
    { artist: 'Carole King',                  title: 'Tapestry' },
    { artist: 'The Rolling Stones',           title: 'Exile on Main St.' },
    { artist: 'John Coltrane',                title: 'A Love Supreme' },
    { artist: 'N.W.A',                        title: 'Straight Outta Compton' },
    { artist: 'My Bloody Valentine',          title: 'Loveless' },
    { artist: 'The Smiths',                   title: 'The Queen Is Dead' },
    { artist: "D'Angelo",                     title: 'Brown Sugar' },
    { artist: 'The Stooges',                  title: 'Raw Power' },
    { artist: 'Television',                   title: 'Marquee Moon' },
    { artist: "Guns N' Roses",                title: 'Appetite for Destruction' },
    { artist: 'Beastie Boys',                 title: 'Licensed to Ill' },
    { artist: 'Nine Inch Nails',              title: 'The Downward Spiral' },
    { artist: 'Dr. Dre',                      title: 'The Chronic' },
    { artist: 'Massive Attack',               title: 'Blue Lines' },
    { artist: 'Kate Bush',                    title: 'Hounds of Love' },
  ],
};

module.exports = { FEATURED_PLAYLIST_META, PLAYLIST_ALBUMS };
