// Hardcoded genre album lists — 12 genres × 48 albums each.
// Used by /api/admin/populate-genres to seed the genre_albums table via AM search.

const GENRE_ALBUMS = {
  'Hip-Hop / Rap': [
    { artist: 'Travis Scott',            title: 'Utopia' },
    { artist: 'Drake',                   title: 'For All the Dogs' },
    { artist: 'Future & Metro Boomin',   title: 'We Don\'t Trust You' },
    { artist: 'Metro Boomin',            title: 'Heroes & Villains' },
    { artist: 'Lil Uzi Vert',           title: 'Pink Tape' },
    { artist: 'Playboi Carti',          title: 'Whole Lotta Red' },
    { artist: 'Gunna',                   title: 'A Gift & a Curse' },
    { artist: 'Lil Baby',               title: 'My Turn' },
    { artist: '21 Savage',              title: 'American Dream' },
    { artist: 'Tyler The Creator',      title: 'Call Me If You Get Lost' },
    { artist: 'Kendrick Lamar',         title: 'Mr. Morale & the Big Steppers' },
    { artist: 'J. Cole',                title: 'The Off-Season' },
    { artist: 'Cardi B',                title: 'Invasion of Privacy' },
    { artist: 'Megan Thee Stallion',    title: 'Traumazine' },
    { artist: 'A$AP Rocky',             title: 'Testing' },
    { artist: 'Nas',                    title: 'Illmatic' },
    { artist: 'Kendrick Lamar',         title: 'To Pimp a Butterfly' },
    { artist: 'Kanye West',             title: 'My Beautiful Dark Twisted Fantasy' },
    { artist: 'A Tribe Called Quest',   title: 'The Low End Theory' },
    { artist: 'OutKast',                title: 'Aquemini' },
    { artist: 'Jay-Z',                  title: 'The Blueprint' },
    { artist: 'Wu-Tang Clan',           title: 'Enter the Wu-Tang (36 Chambers)' },
    { artist: 'Dr. Dre',                title: 'The Chronic' },
    { artist: 'Lauryn Hill',            title: 'The Miseducation of Lauryn Hill' },
    { artist: 'Public Enemy',           title: 'It Takes a Nation of Millions to Hold Us Back' },
    { artist: 'The Notorious B.I.G.',   title: 'Ready to Die' },
    { artist: 'Tupac',                  title: 'All Eyez on Me' },
    { artist: 'Run-D.M.C.',             title: 'Raising Hell' },
    { artist: 'MF DOOM',               title: 'Madvillainy' },
    { artist: 'Kanye West',             title: 'The College Dropout' },
    { artist: '50 Cent',               title: 'Get Rich or Die Tryin\'' },
    { artist: 'N.W.A',                  title: 'Straight Outta Compton' },
    { artist: 'Travis Scott',           title: 'Astroworld' },
    { artist: 'Future',                 title: 'DS2' },
    { artist: 'Playboi Carti',          title: 'Die Lit' },
    { artist: 'Young Thug',             title: 'Barter 6' },
    { artist: 'Lil Wayne',              title: 'Tha Carter III' },
    { artist: 'Tyler The Creator',      title: 'Igor' },
    { artist: 'Kendrick Lamar',         title: 'Good Kid M.A.A.D City' },
    { artist: 'Drake',                  title: 'Take Care' },
    { artist: 'Jay-Z',                  title: 'Reasonable Doubt' },
    { artist: 'Missy Elliott',          title: 'Supa Dupa Fly' },
    { artist: 'OutKast',                title: 'Stankonia' },
    { artist: 'Clipse',                 title: 'Hell Hath No Fury' },
    { artist: 'Pusha T',                title: 'Daytona' },
    { artist: 'Danny Brown',            title: 'Atrocity Exhibition' },
    { artist: 'Freddie Gibbs & Madlib', title: 'Pinata' },
    { artist: 'Denzel Curry',           title: 'Melt My Eyez See Your Future' },
  ],

  'Pop': [
    { artist: 'Taylor Swift',       title: 'The Tortured Poets Department' },
    { artist: 'Olivia Rodrigo',     title: 'Guts' },
    { artist: 'Billie Eilish',      title: 'Hit Me Hard and Soft' },
    { artist: 'Sabrina Carpenter',  title: 'Short n\' Sweet' },
    { artist: 'The Weeknd',         title: 'After Hours' },
    { artist: 'Dua Lipa',           title: 'Future Nostalgia' },
    { artist: 'Harry Styles',       title: 'Harry\'s House' },
    { artist: 'Ariana Grande',      title: 'Eternal Sunshine' },
    { artist: 'Miley Cyrus',        title: 'Endless Summer Vacation' },
    { artist: 'Ed Sheeran',         title: 'Divide' },
    { artist: 'Adele',              title: '30' },
    { artist: 'Justin Bieber',      title: 'Justice' },
    { artist: 'Doja Cat',           title: 'Scarlet' },
    { artist: 'Lana Del Rey',       title: 'Did You Know That There\'s a Tunnel Under Ocean Blvd' },
    { artist: 'SZA',                title: 'SOS' },
    { artist: 'Michael Jackson',    title: 'Thriller' },
    { artist: 'Madonna',            title: 'Like a Prayer' },
    { artist: 'Prince',             title: 'Purple Rain' },
    { artist: 'ABBA',               title: 'Arrival' },
    { artist: 'George Michael',     title: 'Faith' },
    { artist: 'Whitney Houston',    title: 'Whitney Houston' },
    { artist: 'Cyndi Lauper',       title: 'She\'s So Unusual' },
    { artist: 'Britney Spears',     title: 'Baby One More Time' },
    { artist: 'Lady Gaga',          title: 'The Fame Monster' },
    { artist: 'Katy Perry',         title: 'Teenage Dream' },
    { artist: 'Taylor Swift',       title: '1989' },
    { artist: 'Lorde',              title: 'Melodrama' },
    { artist: 'Charli XCX',         title: 'Brat' },
    { artist: 'Robyn',              title: 'Body Talk' },
    { artist: 'Madonna',            title: 'Ray of Light' },
    { artist: 'Prince',             title: 'Sign o\' the Times' },
    { artist: 'Janet Jackson',      title: 'Rhythm Nation 1814' },
    { artist: 'Beyonce',            title: 'Beyonce' },
    { artist: 'Beyonce',            title: 'Lemonade' },
    { artist: 'Rihanna',            title: 'Anti' },
    { artist: 'Dua Lipa',           title: 'Radical Optimism' },
    { artist: 'Olivia Rodrigo',     title: 'Sour' },
    { artist: 'Billie Eilish',      title: 'When We All Fall Asleep Where Do We Go' },
    { artist: 'Ariana Grande',      title: 'Thank U Next' },
    { artist: 'Adele',              title: '21' },
    { artist: 'Justin Timberlake',  title: 'FutureSex LoveSounds' },
    { artist: 'Kylie Minogue',      title: 'Fever' },
    { artist: 'Lana Del Rey',       title: 'Born to Die' },
    { artist: 'Troye Sivan',        title: 'Something to Give Each Other' },
    { artist: 'Carly Rae Jepsen',   title: 'Emotion' },
    { artist: 'Tate McRae',         title: 'Think Later' },
    { artist: 'Selena Gomez',       title: 'Rare' },
    { artist: 'Post Malone',        title: 'Hollywood\'s Bleeding' },
  ],

  'Rock': [
    { artist: 'Arctic Monkeys',         title: 'The Car' },
    { artist: 'Foo Fighters',           title: 'But Here We Are' },
    { artist: 'Paramore',               title: 'This Is Why' },
    { artist: 'Sam Fender',             title: 'Seventeen Going Under' },
    { artist: 'Maneskin',               title: 'Rush!' },
    { artist: 'The Killers',            title: 'Pressure Machine' },
    { artist: 'Greta Van Fleet',        title: 'Starcatcher' },
    { artist: 'Royal Blood',            title: 'Back to the Water Below' },
    { artist: 'Queens of the Stone Age', title: 'In Times New Roman' },
    { artist: 'The 1975',               title: 'Being Funny in a Foreign Language' },
    { artist: 'IDLES',                  title: 'Crawler' },
    { artist: 'Nothing But Thieves',    title: 'Dead Club City' },
    { artist: 'Fontaines D.C.',         title: 'Skinty Fia' },
    { artist: 'The Last Dinner Party',  title: 'Prelude to Ecstasy' },
    { artist: 'Wolf Alice',             title: 'Blue Weekend' },
    { artist: 'The Beatles',            title: 'Abbey Road' },
    { artist: 'Pink Floyd',             title: 'The Dark Side of the Moon' },
    { artist: 'Led Zeppelin',           title: 'Led Zeppelin IV' },
    { artist: 'The Rolling Stones',     title: 'Exile on Main St.' },
    { artist: 'Nirvana',                title: 'Nevermind' },
    { artist: 'Radiohead',              title: 'OK Computer' },
    { artist: 'Fleetwood Mac',          title: 'Rumours' },
    { artist: 'Bruce Springsteen',      title: 'Born to Run' },
    { artist: 'The Clash',              title: 'London Calling' },
    { artist: 'AC/DC',                  title: 'Back in Black' },
    { artist: 'U2',                     title: 'The Joshua Tree' },
    { artist: 'Guns N\' Roses',         title: 'Appetite for Destruction' },
    { artist: 'The Who',                title: 'Who\'s Next' },
    { artist: 'David Bowie',            title: 'The Rise and Fall of Ziggy Stardust' },
    { artist: 'Queen',                  title: 'A Night at the Opera' },
    { artist: 'Oasis',                  title: 'What\'s the Story Morning Glory' },
    { artist: 'The Strokes',            title: 'Is This It' },
    { artist: 'Red Hot Chili Peppers',  title: 'Californication' },
    { artist: 'Pearl Jam',              title: 'Ten' },
    { artist: 'R.E.M.',                 title: 'Automatic for the People' },
    { artist: 'The White Stripes',      title: 'Elephant' },
    { artist: 'Kings of Leon',          title: 'Only by the Night' },
    { artist: 'Muse',                   title: 'Origin of Symmetry' },
    { artist: 'The Smashing Pumpkins',  title: 'Siamese Dream' },
    { artist: 'Soundgarden',            title: 'Superunknown' },
    { artist: 'Alice in Chains',        title: 'Dirt' },
    { artist: 'Green Day',              title: 'American Idiot' },
    { artist: 'Blink-182',              title: 'Enema of the State' },
    { artist: 'Fall Out Boy',           title: 'From Under the Cork Tree' },
    { artist: 'My Chemical Romance',    title: 'The Black Parade' },
    { artist: 'Linkin Park',            title: 'Hybrid Theory' },
    { artist: 'Arctic Monkeys',         title: 'Whatever People Say I Am That\'s What I\'m Not' },
    { artist: 'Tame Impala',            title: 'Currents' },
  ],

  'Reggaeton': [
    { artist: 'Selena',                  title: 'Amor Prohibido' },
    { artist: 'Daddy Yankee',            title: 'Barrio Fino' },
    { artist: 'Bad Bunny',               title: 'Un Verano Sin Ti' },
    { artist: 'Bad Bunny',               title: 'YHLQMDLG' },
    { artist: 'Rosalia',                 title: 'El Mal Querer' },
    { artist: 'Rosalia',                 title: 'Motomami' },
    { artist: 'Shakira',                 title: 'Fijacion Oral Vol. 1' },
    { artist: 'Shakira',                 title: 'Donde Estan los Ladrones' },
    { artist: 'Juanes',                  title: 'Mi Sangre' },
    { artist: 'Juan Luis Guerra',        title: 'Bachata Rosa' },
    { artist: 'Manu Chao',               title: 'Clandestino' },
    { artist: 'Cafe Tacvba',             title: 'Re' },
    { artist: 'Soda Stereo',             title: 'Sueno Stereo' },
    { artist: 'Soda Stereo',             title: 'Cancion Animal' },
    { artist: 'Tego Calderon',           title: 'El Abayarde' },
    { artist: 'Shakira',                 title: 'Pies Descalzos' },
    { artist: 'Luis Fonsi',              title: 'Vida' },
    { artist: 'Luis Miguel',             title: 'Romance' },
    { artist: 'Pescado Rabioso',         title: 'Artaud' },
    { artist: 'Charly Garcia',           title: 'Clics Modernos' },
    { artist: 'Fito Paez',               title: 'El Amor Despues del Amor' },
    { artist: 'Buena Vista Social Club', title: 'Buena Vista Social Club' },
    { artist: 'Willie Colon',            title: 'Siembra' },
    { artist: 'Alejandro Sanz',          title: 'Deja Que Te Bese' },
    { artist: 'Gustavo Cerati',          title: '11 Episodios Sinfonicos' },
    { artist: 'Gustavo Cerati',          title: 'Ahi Vamos' },
    { artist: 'Ricky Martin',            title: 'Musica Alma Sexo' },
    { artist: 'Aquelarre',               title: 'Aquelarre' },
    { artist: 'Camaron de la Isla',      title: 'La Leyenda del Tiempo' },
    { artist: 'Paco de Lucia',           title: 'Fuente y Caudal' },
    { artist: 'Natalia Lafourcade',      title: 'Musas' },
    { artist: 'Natalia Lafourcade',      title: 'Hasta la Raiz' },
    { artist: 'Kali Uchis',              title: 'Sin Miedo del Amor y Otros Demonios' },
    { artist: 'Kali Uchis',              title: 'Por Vida' },
    { artist: 'Karol G',                 title: 'Manana Sera Bonito' },
    { artist: 'Karol G',                 title: 'KG0516' },
    { artist: 'Rauw Alejandro',          title: 'Vice Versa' },
    { artist: 'Rauw Alejandro',          title: 'Afrodisiaco' },
    { artist: 'Tainy',                   title: 'Data' },
    { artist: 'J Balvin',                title: 'Energia' },
    { artist: 'J Balvin',                title: 'Colores' },
    { artist: 'J Balvin',                title: 'Vibras' },
    { artist: 'J Balvin',                title: 'Oasis' },
    { artist: 'Daddy Yankee',            title: 'Legendaddy' },
    { artist: 'Rauw Alejandro',          title: 'Saturno' },
    { artist: 'Thalia',                  title: 'En Extasis' },
    { artist: 'Ricky Martin',            title: 'Pausa' },
    { artist: 'Bad Bunny',               title: 'Debi Tirar Mas Fotos' },
  ],

  'Afrobeats': [
    { artist: 'Burna Boy',      title: 'I Told Them' },
    { artist: 'Rema',           title: 'Rave & Roses' },
    { artist: 'Asake',          title: 'Work of Art' },
    { artist: 'Tems',           title: 'Born in the Wild' },
    { artist: 'Wizkid',         title: 'More Love Less Ego' },
    { artist: 'Davido',         title: 'Timeless' },
    { artist: 'Ayra Starr',     title: 'The Year I Turned 21' },
    { artist: 'Omah Lay',       title: 'Boy Alone' },
    { artist: 'Fireboy DML',    title: 'Playboy' },
    { artist: 'Oxlade',         title: 'Oxlade from Africa' },
    { artist: 'Kizz Daniel',    title: 'Maverick' },
    { artist: 'Joeboy',         title: 'Body & Soul' },
    { artist: 'BNXN',           title: 'Sincerely Benson' },
    { artist: 'Lojay',          title: 'Gangster Romantic' },
    { artist: 'Adekunle Gold',  title: 'Tequila Ever After' },
    { artist: 'Wizkid',         title: 'Made in Lagos' },
    { artist: 'Burna Boy',      title: 'African Giant' },
    { artist: 'Fela Kuti',      title: 'Zombie' },
    { artist: 'Davido',         title: 'A Good Time' },
    { artist: 'Mr Eazi',        title: 'Life Is Eazi Vol. 2' },
    { artist: 'Tiwa Savage',    title: 'Celia' },
    { artist: 'Omah Lay',       title: 'Get Layd' },
    { artist: 'Asake',          title: 'Mr Money with the Vibe' },
    { artist: 'Wizkid',         title: 'Superstar' },
    { artist: 'Burna Boy',      title: 'Twice as Tall' },
    { artist: 'Rema',           title: 'Ravage' },
    { artist: 'Fireboy DML',    title: 'Apollo' },
    { artist: 'Adekunle Gold',  title: 'Catch Me If You Can' },
    { artist: 'Tems',           title: 'If Orange Was a Place' },
    { artist: 'Davido',         title: 'A Better Time' },
    { artist: 'Kizz Daniel',    title: 'No Bad Songz' },
    { artist: 'Joeboy',         title: 'Somewhere Between Beauty & Magic' },
    { artist: 'Mayorkun',       title: 'Back in Office' },
    { artist: 'Olamide',        title: 'Carpe Diem' },
    { artist: 'P-Square',       title: 'Game Over' },
    { artist: '2Baba',          title: 'Face 2 Face' },
    { artist: 'Wizkid',         title: 'Ayo' },
    { artist: 'Burna Boy',      title: 'Outside' },
    { artist: 'Davido',         title: 'Omo Baba Olowo' },
    { artist: 'Tiwa Savage',    title: 'Once Upon a Time' },
    { artist: 'Ayra Starr',     title: '19 & Dangerous' },
    { artist: 'Asake',          title: 'Lungu Boy' },
    { artist: 'Wizkid',         title: 'Soundman Vol. 1' },
    { artist: 'Burna Boy',      title: 'Love Damini' },
    { artist: 'Omah Lay',       title: 'What Have We Done' },
    { artist: 'Davido',         title: 'Son of Mercy' },
    { artist: 'Rema',           title: 'Rema' },
    { artist: 'Oxlade',         title: 'Eclipse' },
  ],

  'R&B / Soul': [
    { artist: 'SZA',               title: 'SOS' },
    { artist: 'Victoria Monet',    title: 'Jaguar II' },
    { artist: 'Brent Faiyaz',      title: 'Wasteland' },
    { artist: 'Summer Walker',     title: 'Still Over It' },
    { artist: 'Giveon',            title: 'Give or Take' },
    { artist: 'H.E.R.',            title: 'Back of My Mind' },
    { artist: 'Daniel Caesar',     title: 'Never Enough' },
    { artist: 'Kali Uchis',        title: 'Red Moon in Venus' },
    { artist: 'Steve Lacy',        title: 'Gemini Rights' },
    { artist: 'Jazmine Sullivan',  title: 'Heaux Tales' },
    { artist: 'Miguel',            title: 'War & Leisure' },
    { artist: 'Kehlani',           title: 'Blue Water Road' },
    { artist: 'Lucky Daye',        title: 'Candydrip' },
    { artist: 'Ari Lennox',        title: 'Age Sex Location' },
    { artist: 'Bryson Tiller',     title: 'Anniversary' },
    { artist: 'Lauryn Hill',       title: 'The Miseducation of Lauryn Hill' },
    { artist: 'Stevie Wonder',     title: 'Songs in the Key of Life' },
    { artist: 'Marvin Gaye',       title: 'What\'s Going On' },
    { artist: 'D\'Angelo',          title: 'Voodoo' },
    { artist: 'Frank Ocean',       title: 'Blonde' },
    { artist: 'Prince',            title: 'Sign o\' the Times' },
    { artist: 'Beyonce',           title: 'Lemonade' },
    { artist: 'Curtis Mayfield',   title: 'Super Fly' },
    { artist: 'Otis Redding',      title: 'Otis Blue' },
    { artist: 'Aretha Franklin',   title: 'I Never Loved a Man the Way I Love You' },
    { artist: 'Al Green',          title: 'Let\'s Stay Together' },
    { artist: 'Janet Jackson',     title: 'The Velvet Rope' },
    { artist: 'Erykah Badu',       title: 'Baduizm' },
    { artist: 'Maxwell',           title: 'Urban Hang Suite' },
    { artist: 'TLC',               title: 'CrazySexyCool' },
    { artist: 'Usher',             title: 'Confessions' },
    { artist: 'Alicia Keys',       title: 'Songs in A Minor' },
    { artist: 'Mary J. Blige',     title: 'My Life' },
    { artist: 'Sade',              title: 'Diamond Life' },
    { artist: 'The Weeknd',        title: 'House of Balloons' },
    { artist: 'Frank Ocean',       title: 'Channel Orange' },
    { artist: 'Beyonce',           title: 'Beyonce' },
    { artist: 'Solange',           title: 'A Seat at the Table' },
    { artist: 'Miguel',            title: 'Kaleidoscope Dream' },
    { artist: 'Anderson Paak',     title: 'Malibu' },
    { artist: 'Chris Brown',       title: 'F.A.M.E.' },
    { artist: 'Rihanna',           title: 'Anti' },
    { artist: 'Jhene Aiko',        title: 'Souled Out' },
    { artist: 'Summer Walker',     title: 'Over It' },
    { artist: 'SZA',               title: 'Ctrl' },
    { artist: 'Daniel Caesar',     title: 'Freudian' },
    { artist: 'Giveon',            title: 'When It\'s All Said and Done' },
    { artist: 'Victoria Monet',    title: 'Jaguar' },
  ],

  'Electronic': [
    { artist: 'Fred again..',        title: 'Actual Life 3' },
    { artist: 'Skrillex',            title: 'Quest for Fire' },
    { artist: 'Peggy Gou',           title: 'I Hear You' },
    { artist: 'Overmono',            title: 'Good Lies' },
    { artist: 'Bicep',               title: 'Isles' },
    { artist: 'Jamie xx',            title: 'In Colour' },
    { artist: 'Kaytranada',          title: 'Bubba' },
    { artist: 'Porter Robinson',     title: 'Nurture' },
    { artist: 'Flume',               title: 'Palaces' },
    { artist: 'Disclosure',          title: 'Settle' },
    { artist: 'Four Tet',            title: 'New Energy' },
    { artist: 'Bonobo',              title: 'Migration' },
    { artist: 'ODESZA',              title: 'The Last Goodbye' },
    { artist: 'Caribou',             title: 'Suddenly' },
    { artist: 'Fred again..',        title: 'Actual Life 2' },
    { artist: 'Daft Punk',           title: 'Discovery' },
    { artist: 'Aphex Twin',          title: 'Selected Ambient Works 85-92' },
    { artist: 'Burial',              title: 'Untrue' },
    { artist: 'Kraftwerk',           title: 'The Man-Machine' },
    { artist: 'Boards of Canada',    title: 'Music Has the Right to Children' },
    { artist: 'The Chemical Brothers', title: 'Dig Your Own Hole' },
    { artist: 'Justice',             title: 'Cross' },
    { artist: 'Moby',                title: 'Play' },
    { artist: 'Fatboy Slim',         title: 'You\'ve Come a Long Way Baby' },
    { artist: 'Underworld',          title: 'Dubnobasswithmyheadman' },
    { artist: 'LCD Soundsystem',     title: 'Sound of Silver' },
    { artist: 'Daft Punk',           title: 'Homework' },
    { artist: 'Aphex Twin',          title: 'Richard D. James Album' },
    { artist: 'Brian Eno',           title: 'Ambient 1 Music for Airports' },
    { artist: 'Massive Attack',      title: 'Mezzanine' },
    { artist: 'The Prodigy',         title: 'The Fat of the Land' },
    { artist: 'Orbital',             title: 'Orbital 2' },
    { artist: 'Autechre',            title: 'Tri Repetae' },
    { artist: 'Arca',                title: 'KiCk i' },
    { artist: 'Sophie',              title: 'Oil of Every Pearl\'s Un-Insides' },
    { artist: 'Charli XCX',          title: 'How I\'m Feeling Now' },
    { artist: 'Jamie xx',            title: 'In Waves' },
    { artist: 'Flume',               title: 'Flume' },
    { artist: 'Deadmau5',            title: 'Random Album Title' },
    { artist: 'Calvin Harris',       title: '18 Months' },
    { artist: 'Avicii',              title: 'True' },
    { artist: 'Swedish House Mafia', title: 'Until Now' },
    { artist: 'Porter Robinson',     title: 'Worlds' },
    { artist: 'Illenium',            title: 'Ashes' },
    { artist: 'Skrillex',            title: 'Scary Monsters and Nice Sprites' },
    { artist: 'Four Tet',            title: 'There Is Love in You' },
    { artist: 'Bonobo',              title: 'Black Sands' },
    { artist: 'Caribou',             title: 'Swim' },
  ],

  'Indie / Alternative': [
    { artist: 'Boygenius',              title: 'The Record' },
    { artist: 'Mitski',                 title: 'The Land Is Inhospitable and So Are We' },
    { artist: 'Big Thief',              title: 'Dragon New Warm Mountain I Believe in You' },
    { artist: 'Phoebe Bridgers',        title: 'Punisher' },
    { artist: 'Alvvays',                title: 'Blue Rev' },
    { artist: 'Snail Mail',             title: 'Valentine' },
    { artist: 'Clairo',                 title: 'Sling' },
    { artist: 'Japanese Breakfast',     title: 'Jubilee' },
    { artist: 'Soccer Mommy',           title: 'Sometimes Forever' },
    { artist: 'beabadoobee',            title: 'Beatopia' },
    { artist: 'Faye Webster',           title: 'Atlanta Millionaires Club' },
    { artist: 'Alex G',                 title: 'God Save the Animals' },
    { artist: 'Sufjan Stevens',         title: 'Javelin' },
    { artist: 'Caroline Polachek',      title: 'Desire I Want to Turn Into You' },
    { artist: 'The National',           title: 'First Two Pages of Frankenstein' },
    { artist: 'Arcade Fire',            title: 'Funeral' },
    { artist: 'The Strokes',            title: 'Is This It' },
    { artist: 'Neutral Milk Hotel',     title: 'In the Aeroplane Over the Sea' },
    { artist: 'Pixies',                 title: 'Doolittle' },
    { artist: 'The Smiths',             title: 'The Queen Is Dead' },
    { artist: 'Modest Mouse',           title: 'The Lonesome Crowded West' },
    { artist: 'Vampire Weekend',        title: 'Vampire Weekend' },
    { artist: 'Tame Impala',            title: 'Currents' },
    { artist: 'Arctic Monkeys',         title: 'Whatever People Say I Am That\'s What I\'m Not' },
    { artist: 'LCD Soundsystem',        title: 'This Is Happening' },
    { artist: 'Interpol',               title: 'Turn on the Bright Lights' },
    { artist: 'MGMT',                   title: 'Oracular Spectacular' },
    { artist: 'Yeah Yeah Yeahs',        title: 'Fever to Tell' },
    { artist: 'TV on the Radio',        title: 'Dear Science' },
    { artist: 'Bon Iver',               title: 'For Emma Forever Ago' },
    { artist: 'Fleet Foxes',            title: 'Fleet Foxes' },
    { artist: 'Grizzly Bear',           title: 'Veckatimest' },
    { artist: 'The xx',                 title: 'xx' },
    { artist: 'The War on Drugs',       title: 'Lost in the Dream' },
    { artist: 'Beach House',            title: 'Teen Dream' },
    { artist: 'Father John Misty',      title: 'I Love You Honeybear' },
    { artist: 'Phoebe Bridgers',        title: 'Stranger in the Alps' },
    { artist: 'Mitski',                 title: 'Be the Cowboy' },
    { artist: 'Big Thief',              title: 'Capacity' },
    { artist: 'Alvvays',                title: 'Antisocialites' },
    { artist: 'Mac DeMarco',            title: 'Salad Days' },
    { artist: 'Tame Impala',            title: 'Lonerism' },
    { artist: 'Foster the People',      title: 'Torches' },
    { artist: 'Glass Animals',          title: 'How to Be a Human Being' },
    { artist: 'Arctic Monkeys',         title: 'AM' },
    { artist: 'Cage the Elephant',      title: 'Melophobia' },
    { artist: 'The Killers',            title: 'Hot Fuss' },
    { artist: 'Florence and the Machine', title: 'Lungs' },
  ],

  'Metal': [
    { artist: 'Sleep Token',             title: 'Take Me Back to Eden' },
    { artist: 'Spiritbox',               title: 'Eternal Blue' },
    { artist: 'Ghost',                   title: 'Impera' },
    { artist: 'Bring Me the Horizon',    title: 'Post Human Survival Horror' },
    { artist: 'Babymetal',               title: 'The Other One' },
    { artist: 'Bad Omens',               title: 'The Death of Peace of Mind' },
    { artist: 'Lorna Shore',             title: 'Pain Remains' },
    { artist: 'Gojira',                  title: 'Fortitude' },
    { artist: 'Architects',              title: 'For Those That Wish to Exist' },
    { artist: 'Trivium',                 title: 'In the Court of the Dragon' },
    { artist: 'Parkway Drive',           title: 'Darker Still' },
    { artist: 'Behemoth',                title: 'Opvs Contra Natvram' },
    { artist: 'Deftones',                title: 'Ohms' },
    { artist: 'Lamb of God',             title: 'Lamb of God' },
    { artist: 'Slipknot',                title: 'The End So Far' },
    { artist: 'Metallica',               title: 'Master of Puppets' },
    { artist: 'Black Sabbath',           title: 'Paranoid' },
    { artist: 'Slayer',                  title: 'Reign in Blood' },
    { artist: 'Iron Maiden',             title: 'The Number of the Beast' },
    { artist: 'Opeth',                   title: 'Blackwater Park' },
    { artist: 'Judas Priest',            title: 'British Steel' },
    { artist: 'Megadeth',                title: 'Rust in Peace' },
    { artist: 'Pantera',                 title: 'Vulgar Display of Power' },
    { artist: 'System of a Down',        title: 'Toxicity' },
    { artist: 'Tool',                    title: 'Lateralus' },
    { artist: 'Deftones',                title: 'White Pony' },
    { artist: 'Slayer',                  title: 'South of Heaven' },
    { artist: 'Metallica',               title: 'Ride the Lightning' },
    { artist: 'Black Sabbath',           title: 'Master of Reality' },
    { artist: 'Iron Maiden',             title: 'Powerslave' },
    { artist: 'Korn',                    title: 'Follow the Leader' },
    { artist: 'Slipknot',                title: 'Iowa' },
    { artist: 'Avenged Sevenfold',       title: 'City of Evil' },
    { artist: 'Mastodon',                title: 'Crack the Skye' },
    { artist: 'Dream Theater',           title: 'Images and Words' },
    { artist: 'Gojira',                  title: 'From Mars to Sirius' },
    { artist: 'Meshuggah',               title: 'ObZen' },
    { artist: 'Dillinger Escape Plan',   title: 'Calculating Infinity' },
    { artist: 'Death',                   title: 'Symbolic' },
    { artist: 'Cannibal Corpse',         title: 'Tomb of the Mutilated' },
    { artist: 'Emperor',                 title: 'In the Nightside Eclipse' },
    { artist: 'Bathory',                 title: 'Under the Sign of the Black Mark' },
    { artist: 'Mayhem',                  title: 'De Mysteriis Dom Sathanas' },
    { artist: 'Burzum',                  title: 'Filosofem' },
    { artist: 'Darkthrone',              title: 'Transilvanian Hunger' },
    { artist: 'Children of Bodom',       title: 'Follow the Reaper' },
    { artist: 'In Flames',               title: 'The Jester Race' },
    { artist: 'At the Gates',            title: 'Slaughter of the Soul' },
  ],

  'Country': [
    { artist: 'Morgan Wallen',    title: 'One Thing at a Time' },
    { artist: 'Zach Bryan',       title: 'Zach Bryan' },
    { artist: 'Luke Combs',       title: 'Gettin\' Old' },
    { artist: 'Kacey Musgraves',  title: 'Deeper Well' },
    { artist: 'Chris Stapleton',  title: 'Starting Over' },
    { artist: 'Lainey Wilson',    title: 'Bell Bottom Country' },
    { artist: 'Tyler Childers',   title: 'Rustin\' in the Rain' },
    { artist: 'Cody Johnson',     title: 'Leather' },
    { artist: 'HARDY',            title: 'The Mockingbird & the Crow' },
    { artist: 'Jelly Roll',       title: 'Whitsitt Chapel' },
    { artist: 'Kane Brown',       title: 'Different Man' },
    { artist: 'Miranda Lambert',  title: 'Palomino' },
    { artist: 'Eric Church',      title: 'Heart & Soul' },
    { artist: 'Ashley McBryde',   title: 'Lindeville' },
    { artist: 'Parker McCollum',  title: 'Never Enough' },
    { artist: 'Johnny Cash',      title: 'At Folsom Prison' },
    { artist: 'Willie Nelson',    title: 'Red Headed Stranger' },
    { artist: 'Dolly Parton',     title: 'Coat of Many Colors' },
    { artist: 'Hank Williams',    title: '40 Greatest Hits' },
    { artist: 'Sturgill Simpson', title: 'Metamodern Sounds in Country Music' },
    { artist: 'Kacey Musgraves',  title: 'Golden Hour' },
    { artist: 'Garth Brooks',     title: 'No Fences' },
    { artist: 'Shania Twain',     title: 'Come On Over' },
    { artist: 'Taylor Swift',     title: 'Fearless' },
    { artist: 'Waylon Jennings',  title: 'Dreaming My Dreams' },
    { artist: 'Merle Haggard',    title: 'Okie from Muskogee' },
    { artist: 'George Jones',     title: 'I Am What I Am' },
    { artist: 'Emmylou Harris',   title: 'Pieces of the Sky' },
    { artist: 'Kris Kristofferson', title: 'Kristofferson' },
    { artist: 'Townes Van Zandt', title: 'Townes Van Zandt' },
    { artist: 'Willie Nelson',    title: 'Stardust' },
    { artist: 'Johnny Cash',      title: 'American IV The Man Comes Around' },
    { artist: 'Chris Stapleton',  title: 'Traveller' },
    { artist: 'Tyler Childers',   title: 'Purgatory' },
    { artist: 'Zach Bryan',       title: 'American Heartbreak' },
    { artist: 'Luke Combs',       title: 'This One\'s for You' },
    { artist: 'Morgan Wallen',    title: 'Dangerous The Double Album' },
    { artist: 'Miranda Lambert',  title: 'Revolution' },
    { artist: 'Carrie Underwood', title: 'Some Hearts' },
    { artist: 'Brad Paisley',     title: 'Mud on the Tires' },
    { artist: 'Keith Urban',      title: 'Golden Road' },
    { artist: 'Kenny Chesney',    title: 'No Shoes No Shirt No Problems' },
    { artist: 'Alan Jackson',     title: 'A Lot About Livin\'' },
    { artist: 'Dwight Yoakam',    title: 'Guitars Cadillacs Etc.' },
    { artist: 'Brooks & Dunn',    title: 'Brand New Man' },
    { artist: 'Florida Georgia Line', title: 'Here\'s to the Good Times' },
    { artist: 'Sam Hunt',         title: 'Montevallo' },
    { artist: 'Chris Stapleton',  title: 'From A Room Vol. 1' },
  ],

  'Jazz': [
    { artist: 'Kamasi Washington',          title: 'Fearless Movement' },
    { artist: 'Nubya Garcia',               title: 'Source' },
    { artist: 'Makaya McCraven',            title: 'In These Times' },
    { artist: 'Alfa Mist',                  title: 'Variables' },
    { artist: 'Shabaka',                    title: 'Perceive Its Beauty Acknowledge Its Grace' },
    { artist: 'Robert Glasper',             title: 'Black Radio' },
    { artist: 'Terrace Martin',             title: 'Dinner Party' },
    { artist: 'Christian Scott',            title: 'Ancestral Recall' },
    { artist: 'Esperanza Spalding',         title: 'Emily\'s D+Evolution' },
    { artist: 'Thundercat',                 title: 'It Is What It Is' },
    { artist: 'BADBADNOTGOOD',              title: 'IV' },
    { artist: 'Yussef Dayes',               title: 'Black Classical Music' },
    { artist: 'Moses Boyd',                 title: 'Dark Matter' },
    { artist: 'Joel Ross',                  title: 'KingMaker' },
    { artist: 'Nubya Garcia',               title: 'Odyssey' },
    { artist: 'Miles Davis',                title: 'Kind of Blue' },
    { artist: 'John Coltrane',              title: 'A Love Supreme' },
    { artist: 'Charles Mingus',             title: 'The Black Saint and the Sinner Lady' },
    { artist: 'Dave Brubeck',               title: 'Time Out' },
    { artist: 'Herbie Hancock',             title: 'Head Hunters' },
    { artist: 'Ornette Coleman',            title: 'The Shape of Jazz to Come' },
    { artist: 'Duke Ellington',             title: 'Ellington at Newport' },
    { artist: 'Bill Evans',                 title: 'Sunday at the Village Vanguard' },
    { artist: 'Weather Report',             title: 'Heavy Weather' },
    { artist: 'Miles Davis',                title: 'Bitches Brew' },
    { artist: 'John Coltrane',              title: 'Giant Steps' },
    { artist: 'Sonny Rollins',              title: 'Saxophone Colossus' },
    { artist: 'Art Blakey',                 title: 'Moanin\'' },
    { artist: 'Thelonious Monk',            title: 'Brilliant Corners' },
    { artist: 'Charles Mingus',             title: 'Mingus Ah Um' },
    { artist: 'Stan Getz & Joao Gilberto',  title: 'Getz Gilberto' },
    { artist: 'Ella Fitzgerald',            title: 'Ella and Louis' },
    { artist: 'Louis Armstrong',            title: 'Louis Armstrong Plays W.C. Handy' },
    { artist: 'Billie Holiday',             title: 'Lady in Satin' },
    { artist: 'Chet Baker',                 title: 'Chet Baker Sings' },
    { artist: 'Keith Jarrett',              title: 'The Koln Concert' },
    { artist: 'Pat Metheny',                title: 'Bright Size Life' },
    { artist: 'Chick Corea',                title: 'Return to Forever' },
    { artist: 'Herbie Hancock',             title: 'Maiden Voyage' },
    { artist: 'Wayne Shorter',              title: 'Speak No Evil' },
    { artist: 'Kamasi Washington',          title: 'The Epic' },
    { artist: 'Esperanza Spalding',         title: 'Esperanza' },
    { artist: 'Brad Mehldau',               title: 'Art of the Trio' },
    { artist: 'Snarky Puppy',               title: 'We Like It Here' },
    { artist: 'GoGo Penguin',               title: 'Man Made Object' },
    { artist: 'Tigran Hamasyan',            title: 'Mockroot' },
    { artist: 'Vijay Iyer',                 title: 'Historicity' },
    { artist: 'Avishai Cohen',              title: 'Gently Disturbed' },
  ],

  'Classical': [
    { artist: 'Glenn Gould',              title: 'Goldberg Variations' },
    { artist: 'Antonio Vivaldi',          title: 'The Four Seasons' },
    { artist: 'Ludwig van Beethoven',     title: 'Symphony No. 9' },
    { artist: 'Wolfgang Amadeus Mozart',  title: 'Requiem' },
    { artist: 'Richard Wagner',           title: 'Der Ring des Nibelung' },
    { artist: 'Gustav Holst',             title: 'The Planets' },
    { artist: 'Maurice Ravel',            title: 'Bolero' },
    { artist: 'Carl Orff',                title: 'Carmina Burana' },
    { artist: 'Igor Stravinsky',          title: 'Rite of Spring' },
    { artist: 'Gustav Mahler',            title: 'Symphony No. 5' },
    { artist: 'Gustav Mahler',            title: 'Symphony No. 9' },
    { artist: 'Robert Schumann',          title: 'Kinderszenen' },
    { artist: 'Frederic Chopin',          title: 'Piano Concertos Nos. 1 & 2' },
    { artist: 'Frederic Chopin',          title: 'Nocturnes' },
    { artist: 'Claude Debussy',           title: 'Clair de Lune' },
    { artist: 'Claude Debussy',           title: 'La Mer' },
    { artist: 'Pyotr Ilyich Tchaikovsky', title: 'Swan Lake' },
    { artist: 'Pyotr Ilyich Tchaikovsky', title: 'The Nutcracker' },
    { artist: 'Pyotr Ilyich Tchaikovsky', title: '1812 Overture' },
    { artist: 'Edvard Grieg',             title: 'Peer Gynt Suites' },
    { artist: 'Hector Berlioz',           title: 'Symphonie Fantastique' },
    { artist: 'Modest Mussorgsky',        title: 'Pictures at an Exhibition' },
    { artist: 'Johann Pachelbel',         title: 'Canon in D' },
    { artist: 'George Frideric Handel',   title: 'Messiah' },
    { artist: 'George Frideric Handel',   title: 'Water Music' },
    { artist: 'Johann Sebastian Bach',    title: 'Brandenburg Concertos' },
    { artist: 'Johann Sebastian Bach',    title: 'Mass in B Minor' },
    { artist: 'Johann Sebastian Bach',    title: 'Cello Suites' },
    { artist: 'Giuseppe Verdi',           title: 'Requiem' },
    { artist: 'Giuseppe Verdi',           title: 'Aida' },
    { artist: 'Georges Bizet',            title: 'Carmen' },
    { artist: 'Giacomo Puccini',          title: 'Madama Butterfly' },
    { artist: 'Giacomo Puccini',          title: 'La Boheme' },
    { artist: 'Giacomo Puccini',          title: 'Turandot' },
    { artist: 'Richard Strauss',          title: 'Also sprach Zarathustra' },
    { artist: 'Richard Strauss',          title: 'Ein Heldenleben' },
    { artist: 'Nikolai Rimsky-Korsakov',  title: 'Scheherazade' },
    { artist: 'Sergei Rachmaninoff',      title: 'Piano Concerto No. 2' },
    { artist: 'Sergei Rachmaninoff',      title: 'Symphony No. 2' },
    { artist: 'Philip Glass',             title: 'Glassworks' },
    { artist: 'Steve Reich',              title: 'Music for 18 Musicians' },
    { artist: 'Floating Points',          title: 'Promises' },
    { artist: 'Arvo Part',               title: 'Tabula Rasa' },
    { artist: 'Arvo Part',               title: 'Spiegel im Spiegel' },
    { artist: 'Samuel Barber',            title: 'Adagio for Strings' },
    { artist: 'Aaron Copland',            title: 'Appalachian Spring' },
    { artist: 'Leonard Bernstein',        title: 'West Side Story' },
    { artist: 'Henryk Gorecki',           title: 'Symphony No. 3' },
  ],

  'Blues': [
    { artist: 'Stevie Ray Vaughan',              title: 'The Sky Is Crying' },
    { artist: 'Stevie Ray Vaughan',              title: 'Texas Flood' },
    { artist: 'Stevie Ray Vaughan',              title: 'Couldn\'t Stand the Weather' },
    { artist: 'Albert King',                     title: 'Born Under a Bad Sign' },
    { artist: 'B.B. King',                       title: 'Live at the Regal' },
    { artist: 'B.B. King',                       title: 'Completely Well' },
    { artist: 'John Mayall',                     title: 'Blues Breakers with Eric Clapton' },
    { artist: 'Derek and the Dominos',           title: 'Layla and Other Assorted Love Songs' },
    { artist: 'The Allman Brothers Band',        title: 'At Fillmore East' },
    { artist: 'Muddy Waters',                    title: 'Folk Singer' },
    { artist: 'Muddy Waters',                    title: 'Hard Again' },
    { artist: 'Robert Johnson',                  title: 'King of the Delta Blues Singers' },
    { artist: 'Howlin\' Wolf',                   title: 'The Real Folk Blues' },
    { artist: 'Howlin\' Wolf',                   title: 'Moanin\' in the Moonlight' },
    { artist: 'Junior Wells',                    title: 'Hoodoo Man Blues' },
    { artist: 'The Paul Butterfield Blues Band', title: 'The Paul Butterfield Blues Band' },
    { artist: 'Albert Collins',                  title: 'Ice Pickin\'' },
    { artist: 'Robert Cray',                     title: 'Strong Persuader' },
    { artist: 'Buddy Guy',                       title: 'Damn Right I\'ve Got the Blues' },
    { artist: 'Buddy Guy',                       title: 'Feels Like Rain' },
    { artist: 'The Black Keys',                  title: 'Chulahoma' },
    { artist: 'The Black Keys',                  title: 'Brothers' },
    { artist: 'Muddy Waters',                    title: 'Electric Mud' },
    { artist: 'B.B. King',                       title: 'Riding with the King' },
    { artist: 'Joe Bonamassa',                   title: 'Blues Deluxe' },
    { artist: 'Gary Clark Jr.',                  title: 'Blak and Blu' },
    { artist: 'R.L. Burnside',                   title: 'Come On In' },
    { artist: 'Dan Auerbach',                    title: 'Keep It Hid' },
    { artist: 'The White Stripes',               title: 'Elephant' },
    { artist: 'John Lee Hooker',                 title: 'John Lee Hooker Sings the Blues' },
    { artist: 'John Lee Hooker',                 title: 'The Healer' },
    { artist: 'Willie Dixon',                    title: 'I Am the Blues' },
    { artist: 'Muddy Waters',                    title: 'Trouble No More' },
    { artist: 'Rory Gallagher',                  title: 'Deuce' },
    { artist: 'Rory Gallagher',                  title: 'Irish Tour \'74' },
    { artist: 'John Mayall',                     title: 'Crusade' },
    { artist: 'Led Zeppelin',                    title: 'Led Zeppelin' },
    { artist: 'ZZ Top',                          title: 'Tres Hombres' },
    { artist: 'John Mayer',                      title: 'Continuum' },
    { artist: 'Samantha Fish',                   title: 'Room on Fire' },
    { artist: 'The Black Keys',                  title: 'Delta Kream' },
    { artist: 'Muddy Waters',                    title: 'Fathers and Sons' },
    { artist: 'John Mayall',                     title: 'Blues from Laurel Canyon' },
    { artist: 'Gary Moore',                      title: 'Still Got the Blues' },
    { artist: 'Stevie Ray Vaughan',              title: 'In Step' },
    { artist: 'Gary Clark Jr.',                  title: 'Dust & Bones' },
    { artist: 'The White Stripes',               title: 'Get Behind Me Satan' },
    { artist: 'Cat Stevens',                     title: 'Tea for the Tillerman' },
  ],

  'Folk / Singer-Songwriter': [
    { artist: 'Noah Kahan',           title: 'Stick Season' },
    { artist: 'Adrianne Lenker',      title: 'Bright Future' },
    { artist: 'Sufjan Stevens',       title: 'Javelin' },
    { artist: 'Phoebe Bridgers',      title: 'Punisher' },
    { artist: 'Bon Iver',             title: 'i i' },
    { artist: 'Gregory Alan Isakov', title: 'Appaloosa Bones' },
    { artist: 'Noah Cyrus',           title: 'The Hardest Part' },
    { artist: 'Madison Cunningham',   title: 'Revealer' },
    { artist: 'Laura Marling',        title: 'Song for Our Daughter' },
    { artist: 'Hozier',               title: 'Unreal Unearth' },
    { artist: 'Fleet Foxes',          title: 'Shore' },
    { artist: 'Sufjan Stevens',       title: 'Carrie & Lowell' },
    { artist: 'Phoebe Bridgers',      title: 'Stranger in the Alps' },
    { artist: 'Bon Iver',             title: 'For Emma Forever Ago' },
    { artist: 'Big Thief',            title: 'U.F.O.F.' },
    { artist: 'Bob Dylan',            title: 'Blood on the Tracks' },
    { artist: 'Joni Mitchell',        title: 'Blue' },
    { artist: 'Nick Drake',           title: 'Pink Moon' },
    { artist: 'Leonard Cohen',        title: 'Songs of Leonard Cohen' },
    { artist: 'Simon & Garfunkel',    title: 'Bridge Over Troubled Water' },
    { artist: 'Cat Stevens',          title: 'Tea for the Tillerman' },
    { artist: 'James Taylor',         title: 'Sweet Baby James' },
    { artist: 'Neil Young',           title: 'Harvest' },
    { artist: 'Carole King',          title: 'Tapestry' },
    { artist: 'Joan Baez',            title: 'Joan Baez' },
    { artist: 'Townes Van Zandt',     title: 'Townes Van Zandt' },
    { artist: 'John Prine',           title: 'John Prine' },
    { artist: 'Jackson Browne',       title: 'Late for the Sky' },
    { artist: 'Van Morrison',         title: 'Astral Weeks' },
    { artist: 'Nick Drake',           title: 'Five Leaves Left' },
    { artist: 'Elliott Smith',        title: 'Either Or' },
    { artist: 'Damien Rice',          title: 'O' },
    { artist: 'Jose Gonzalez',        title: 'Veneer' },
    { artist: 'Iron & Wine',          title: 'Our Endless Numbered Days' },
    { artist: 'Fleet Foxes',          title: 'Fleet Foxes' },
    { artist: 'The Tallest Man on Earth', title: 'The Wild Hunt' },
    { artist: 'Gregory Alan Isakov', title: 'This Empty Northern Hemisphere' },
    { artist: 'Adrianne Lenker',      title: 'Songs' },
    { artist: 'Sufjan Stevens',       title: 'Illinois' },
    { artist: 'Bon Iver',             title: 'Bon Iver' },
    { artist: 'Hozier',               title: 'Hozier' },
    { artist: 'The Lumineers',        title: 'The Lumineers' },
    { artist: 'Mumford & Sons',       title: 'Sigh No More' },
    { artist: 'The Paper Kites',      title: 'Woodland' },
    { artist: 'Ray LaMontagne',       title: 'Trouble' },
    { artist: 'Angus & Julia Stone',  title: 'Down the Way' },
    { artist: 'First Aid Kit',        title: 'Stay Gold' },
    { artist: 'Iron & Wine',          title: 'The Creek Drank the Cradle' },
  ],
};

module.exports = { GENRE_ALBUMS };
