// Hardcoded, ordered "New Releases" list — replaces the old AM most-played
// chart, which lags actual release dates. Order is display order.
// Used by /api/admin/populate-new-releases to seed the new_release_albums table via AM search.

const NEW_RELEASE_ALBUMS = [
  { artist: 'Future',                          title: 'The Real Me' },
  { artist: 'The Rolling Stones',               title: 'Foreign Tongues' },
  { artist: 'Jack White',                       title: 'Frozen Charlotte' },
  { artist: 'Kelela',                           title: 'New Avatar' },
  { artist: 'Madonna',                          title: 'Confessions II' },
  { artist: 'Ken Carson',                       title: 'Xperiment' },
  { artist: 'Mary in the Junkyard',             title: 'Role Model Hermit' },
  { artist: 'Slayyyter',                        title: 'WORST GIRL IN AMERICA' },
  { artist: 'Drake',                            title: 'Iceman' },
  { artist: 'Drake',                            title: 'Habibti' },
  { artist: 'Drake',                            title: 'Maid Of Honour' },
  { artist: 'Don Toliver',                      title: 'OCTANE' },
  { artist: 'Kehlani',                          title: 'Kehlani' },
  { artist: 'Vince Staples',                    title: 'Cry Baby' },
  { artist: 'Lizzo',                            title: 'Bitch' },
  { artist: 'Rick Ross',                        title: 'Set In Stone' },
  { artist: 'Latto',                            title: 'Big Mama' },
  { artist: 'JPEGMafia',                        title: 'Experimental Rap' },
  { artist: '6LACK',                            title: 'Love Is The New Gangsta' },
  { artist: 'Genesis Owusu',                    title: 'Redstar Wu & the Worldwide Scourge' },
  { artist: 'Lucki',                            title: 'Drugs R Bad' },
  { artist: 'BNYX',                             title: 'Genesis-FM' },
  { artist: 'Chris Brown',                      title: 'BROWN' },
  { artist: 'Harry Styles',                     title: 'Kiss All The Time. Disco, Occasionally.' },
  { artist: 'Sabrina Carpenter',                title: 'Man\'s Best Friend' },
  { artist: 'Olivia Dean',                      title: 'The Art of Loving' },
  { artist: 'D12',                              title: 'D12 Forever' },
  { artist: 'Deante\' Hitchcock',               title: 'Junkie in the Sun' },
  { artist: 'Blue Lab Beats',                   title: 'The Blue Lab Beats Show' },
  { artist: 'Panda Bear & Sonic Boom',          title: 'A ? of When' },
  { artist: 'Show Me the Body',                 title: 'Alone Together' },
  { artist: 'Parts & Labor',                    title: 'Set of All Sets' },
  { artist: 'Twisted Teens',                    title: 'Florida Water Blues' },
  { artist: 'Xiu Xiu',                          title: 'Eraserhead Xiu Xiu' },
  { artist: 'Sad13',                            title: '1331' },
  { artist: 'Gloorp',                           title: 'Gloorp Life' },
  { artist: 'Thaiboy Digital',                  title: 'Paradise' },
  { artist: 'Stephen Sanchez',                  title: 'Love, Love, Love' },
  { artist: 'Crown Lands',                      title: 'Apocalypse' },
  { artist: 'Dead Pony',                        title: 'Eat My Dust!' },
  { artist: 'All-American Rejects',             title: 'Sandbox' },
  { artist: '49 Winchester',                    title: 'Change of Plans' },
  { artist: 'Maluma',                           title: 'Loco x Volver' },
  { artist: 'Taeyong',                          title: 'Wyld' },
  { artist: 'Kwes Darko',                       title: 'Altitude' },
  { artist: 'Zsela, Daniel Aged & Taul Katz',   title: '4 Dreams' },
  { artist: 'War on Women',                     title: 'Time Under Tension' },
  { artist: 'Gun Outfit',                       title: 'Unfelt Loss' },
];

module.exports = { NEW_RELEASE_ALBUMS };
