// Curated album/artist lists that drive the cron refresh.
// These mirror the hardcoded data that was previously in the React Native app.

const PLACEHOLDER_ARTISTS = [
  { name: 'Kendrick Lamar',    genre: 'Rap'       },
  { name: 'Taylor Swift',      genre: 'Pop'       },
  { name: 'SZA',               genre: 'R&B'       },
  { name: 'Tyler the Creator', genre: 'Rap'       },
  { name: 'Billie Eilish',     genre: 'Pop'       },
  { name: 'Bad Bunny',         genre: 'Reggaeton' },
  { name: 'The Weeknd',        genre: 'R&B'       },
  { name: 'Chappell Roan',     genre: 'Pop'       },
];

const GENRES = [
  {
    label: 'Rap',
    albums: [
      { album: 'DAMN.',                             artist: 'Kendrick Lamar'  },
      { album: 'Take Care',                         artist: 'Drake'           },
      { album: 'To Pimp a Butterfly',               artist: 'Kendrick Lamar'  },
      { album: 'ASTROWORLD',                        artist: 'Travis Scott'    },
      { album: '2014 Forest Hills Drive',           artist: 'J. Cole'         },
      { album: 'My Beautiful Dark Twisted Fantasy', artist: 'Kanye West'      },
      { album: 'The Blueprint',                     artist: 'JAY-Z'           },
      { album: 'Illmatic',                          artist: 'Nas'             },
      { album: 'good kid, m.A.A.d city',            artist: 'Kendrick Lamar'  },
      { album: 'The Marshall Mathers LP',           artist: 'Eminem'          },
    ],
  },
  {
    label: 'R&B',
    albums: [
      { album: 'After Hours',       artist: 'The Weeknd'    },
      { album: 'SOS',               artist: 'SZA'           },
      { album: 'Lemonade',          artist: 'Beyoncé'       },
      { album: 'channel ORANGE',    artist: 'Frank Ocean'   },
      { album: 'Freudian',          artist: 'Daniel Caesar' },
      { album: 'WASTELAND',         artist: 'Brent Faiyaz'  },
      { album: 'Still Over It',     artist: 'Summer Walker' },
      { album: 'Starboy',           artist: 'The Weeknd'    },
      { album: 'American Teen',     artist: 'Khalid'        },
      { album: 'Back of My Mind',   artist: 'H.E.R.'        },
    ],
  },
  {
    label: 'Pop',
    albums: [
      { album: 'folklore',                              artist: 'Taylor Swift'  },
      { album: 'Midnights',                             artist: 'Taylor Swift'  },
      { album: '30',                                    artist: 'Adele'         },
      { album: 'Future Nostalgia',                      artist: 'Dua Lipa'      },
      { album: "Harry's House",                         artist: 'Harry Styles'  },
      { album: 'SOUR',                                  artist: 'Olivia Rodrigo'},
      { album: 'When We All Fall Asleep Where Do We Go',artist: 'Billie Eilish' },
      { album: 'Divide',                                artist: 'Ed Sheeran'    },
      { album: 'thank u, next',                         artist: 'Ariana Grande' },
      { album: "Hollywood's Bleeding",                  artist: 'Post Malone'   },
    ],
  },
  {
    label: 'Rock',
    albums: [
      { album: 'AM',                artist: 'Arctic Monkeys'          },
      { album: 'OK Computer',       artist: 'Radiohead'               },
      { album: 'Is This It',        artist: 'The Strokes'             },
      { album: 'Currents',          artist: 'Tame Impala'             },
      { album: 'El Camino',         artist: 'The Black Keys'          },
      { album: 'Wasting Light',     artist: 'Foo Fighters'            },
      { album: 'Stadium Arcadium',  artist: 'Red Hot Chili Peppers'   },
      { album: '...Like Clockwork', artist: 'Queens of the Stone Age' },
      { album: 'Origin of Symmetry',artist: 'Muse'                    },
      { album: "Whatever People Say I Am, That's What I'm Not", artist: 'Arctic Monkeys' },
    ],
  },
  {
    label: 'House',
    albums: [
      { album: 'Random Access Memories', artist: 'Daft Punk'    },
      { album: 'Discovery',              artist: 'Daft Punk'    },
      { album: 'Settle',                 artist: 'Disclosure'   },
      { album: 'Caracal',                artist: 'Disclosure'   },
      { album: 'In Colour',              artist: 'Jamie xx'     },
      { album: 'There Is Love In You',   artist: 'Four Tet'     },
      { album: 'Swim',                   artist: 'Caribou'      },
      { album: 'Motion',                 artist: 'Calvin Harris' },
      { album: 'Actual Life 3',          artist: 'Fred again..' },
      { album: 'Black Sands',            artist: 'Bonobo'       },
    ],
  },
  {
    label: 'Jazz',
    albums: [
      { album: 'Kind of Blue',        artist: 'Miles Davis'          },
      { album: 'A Love Supreme',      artist: 'John Coltrane'        },
      { album: 'Time Out',            artist: 'Dave Brubeck Quartet' },
      { album: 'Head Hunters',        artist: 'Herbie Hancock'       },
      { album: 'Waltz for Debby',     artist: 'Bill Evans'           },
      { album: 'Mingus Ah Um',        artist: 'Charles Mingus'       },
      { album: 'Chet Baker Sings',    artist: 'Chet Baker'           },
      { album: 'Saxophone Colossus',  artist: 'Sonny Rollins'        },
      { album: 'Sketches of Spain',   artist: 'Miles Davis'          },
      { album: "Monk's Dream",        artist: 'Thelonious Monk'      },
    ],
  },
  {
    label: 'Soul',
    albums: [
      { album: "What's Going On",                 artist: 'Marvin Gaye'    },
      { album: 'Back to Black',                   artist: 'Amy Winehouse'  },
      { album: 'The Miseducation of Lauryn Hill',  artist: 'Ms. Lauryn Hill'},
      { album: 'Songs in the Key of Life',         artist: 'Stevie Wonder'  },
      { album: 'Voodoo',                           artist: "D'Angelo"       },
      { album: 'A Seat at the Table',              artist: 'Solange'        },
      { album: 'Baduizm',                          artist: 'Erykah Badu'   },
      { album: 'Get Lifted',                       artist: 'John Legend'    },
      { album: 'Songs in A Minor',                 artist: 'Alicia Keys'    },
      { album: 'Coming Home',                      artist: 'Leon Bridges'   },
    ],
  },
  {
    label: 'Country',
    albums: [
      { album: 'Dangerous: The Double Album',        artist: 'Morgan Wallen'    },
      { album: 'Golden Hour',                        artist: 'Kacey Musgraves'  },
      { album: 'Traveller',                          artist: 'Chris Stapleton'  },
      { album: 'American Heartbreak',                artist: 'Zach Bryan'       },
      { album: "This One's for You",                 artist: 'Luke Combs'       },
      { album: 'Purgatory',                          artist: 'Tyler Childers'   },
      { album: 'Metamodern Sounds in Country Music', artist: 'Sturgill Simpson' },
      { album: 'By the Way, I Forgive You',          artist: 'Brandi Carlile'   },
      { album: 'Southeastern',                       artist: 'Jason Isbell'     },
      { album: 'Stoned Side of the Mtn',             artist: 'Tyler Childers'   },
    ],
  },
];

const DECADES = [
  {
    label: '1950s',
    albums: [
      { album: 'In the Wee Small Hours',                          artist: 'Frank Sinatra'        },
      { album: 'Elvis Presley',                                   artist: 'Elvis Presley'        },
      { album: 'Kind of Blue',                                    artist: 'Miles Davis'          },
      { album: 'Blue Train',                                      artist: 'John Coltrane'        },
      { album: 'Mingus Ah Um',                                    artist: 'Charles Mingus'       },
      { album: "Here's Little Richard",                           artist: 'Little Richard'       },
      { album: 'The "Chirping" Crickets',                         artist: 'Buddy Holly'          },
      { album: 'The Genius of Ray Charles',                       artist: 'Ray Charles'          },
      { album: 'Lady Sings the Blues',                            artist: 'Billie Holiday'       },
      { album: 'Chet Baker Sings',                                artist: 'Chet Baker'           },
      { album: 'Brilliant Corners',                               artist: 'Thelonious Monk'      },
      { album: 'Ella Fitzgerald Sings the Cole Porter Songbook',  artist: 'Ella Fitzgerald'      },
      { album: 'Love Is the Thing',                               artist: 'Nat King Cole'        },
      { album: 'Calypso',                                         artist: 'Harry Belafonte'      },
      { album: 'After School Session',                            artist: 'Chuck Berry'          },
      { album: 'With His Hot and Blue Guitar',                    artist: 'Johnny Cash'          },
      { album: 'Songs Our Daddy Taught Us',                       artist: 'The Everly Brothers'  },
      { album: 'Elvis',                                           artist: 'Elvis Presley'        },
      { album: "Songs for Swingin' Lovers!",                      artist: 'Frank Sinatra'        },
      { album: "What a Diff'rence a Day Makes!",                  artist: 'Dinah Washington'     },
      { album: 'The Shape of Jazz to Come',                       artist: 'Ornette Coleman'      },
      { album: 'Time Out',                                        artist: 'Dave Brubeck'         },
      { album: 'Birth of the Cool',                               artist: 'Miles Davis'          },
      { album: 'Giant Steps',                                     artist: 'John Coltrane'        },
      { album: 'The Best of Muddy Waters',                        artist: 'Muddy Waters'         },
      { album: 'Bo Diddley',                                      artist: 'Bo Diddley'           },
      { album: 'Jerry Lee Lewis',                                 artist: 'Jerry Lee Lewis'      },
      { album: 'Dance Album of Carl Perkins',                     artist: 'Carl Perkins'         },
      { album: 'This Is Fats',                                    artist: 'Fats Domino'          },
      { album: 'Encore',                                          artist: 'Sam Cooke'            },
      { album: 'Louis Armstrong Plays W.C. Handy',                artist: 'Louis Armstrong'      },
      { album: 'Sarah Vaughan with Clifford Brown',               artist: 'Sarah Vaughan'        },
      { album: 'Saxophone Colossus',                              artist: 'Sonny Rollins'        },
      { album: "Moanin'",                                         artist: 'Art Blakey'           },
      { album: 'Ellington at Newport',                            artist: 'Duke Ellington'       },
      { album: 'Bluejean Bop!',                                   artist: 'Gene Vincent'         },
      { album: "Moanin' in the Moonlight",                        artist: "Howlin' Wolf"         },
      { album: "Moanin' the Blues",                               artist: 'Hank Williams'        },
      { album: 'Patsy Cline',                                     artist: 'Patsy Cline'          },
      { album: 'The Platters',                                    artist: 'The Platters'         },
      { album: 'Songs of Our Soil',                               artist: 'Johnny Cash'          },
      { album: 'Pithecanthropus Erectus',                         artist: 'Charles Mingus'       },
      { album: 'Night Lights',                                    artist: 'Gerry Mulligan'       },
      { album: 'Sonny Side Up',                                   artist: 'Dizzy Gillespie'      },
      { album: 'Lady in Satin',                                   artist: 'Billie Holiday'       },
      { album: 'Little Girl Blue',                                artist: 'Nina Simone'          },
      { album: 'At the Pershing: But Not for Me',                 artist: 'Ahmad Jamal'          },
      { album: 'The Kingston Trio',                               artist: 'The Kingston Trio'    },
    ],
  },
  {
    label: '1960s',
    albums: [
      { album: "Sgt. Pepper's Lonely Hearts Club Band", artist: 'The Beatles'                  },
      { album: 'Revolver',                              artist: 'The Beatles'                  },
      { album: 'Rubber Soul',                           artist: 'The Beatles'                  },
      { album: 'Abbey Road',                            artist: 'The Beatles'                  },
      { album: 'Highway 61 Revisited',                  artist: 'Bob Dylan'                    },
      { album: 'Blonde on Blonde',                      artist: 'Bob Dylan'                    },
      { album: 'Pet Sounds',                            artist: 'The Beach Boys'               },
      { album: 'The Velvet Underground & Nico',         artist: 'The Velvet Underground & Nico'},
      { album: 'Are You Experienced',                   artist: 'Jimi Hendrix'                 },
      { album: 'Electric Ladyland',                     artist: 'Jimi Hendrix'                 },
      { album: 'Let It Bleed',                          artist: 'The Rolling Stones'           },
      { album: 'Beggars Banquet',                       artist: 'The Rolling Stones'           },
      { album: 'The Doors',                             artist: 'The Doors'                    },
      { album: 'Strange Days',                          artist: 'The Doors'                    },
      { album: 'I Never Loved a Man the Way I Love You',artist: 'Aretha Franklin'              },
      { album: 'Lady Soul',                             artist: 'Aretha Franklin'              },
      { album: 'In the Groove',                         artist: 'Marvin Gaye'                  },
      { album: 'Wild Is the Wind',                      artist: 'Nina Simone'                  },
      { album: 'Bridge Over Troubled Water',            artist: 'Simon & Garfunkel'            },
      { album: 'Bookends',                              artist: 'Simon & Garfunkel'            },
      { album: 'Led Zeppelin',                          artist: 'Led Zeppelin'                 },
      { album: 'Led Zeppelin II',                       artist: 'Led Zeppelin'                 },
      { album: 'In the Court of the Crimson King',      artist: 'King Crimson'                 },
      { album: 'Tommy',                                 artist: 'The Who'                      },
      { album: 'My Generation',                         artist: 'The Who'                      },
      { album: 'Forever Changes',                       artist: 'Love'                         },
      { album: 'Astral Weeks',                          artist: 'Van Morrison'                 },
      { album: 'Green River',                           artist: 'Creedence Clearwater Revival' },
      { album: 'Willy and the Poor Boys',               artist: 'Creedence Clearwater Revival' },
      { album: 'Otis Blue',                             artist: 'Otis Redding'                 },
      { album: 'A Love Supreme',                        artist: 'John Coltrane'                },
      { album: 'In a Silent Way',                       artist: 'Miles Davis'                  },
      { album: 'Bitches Brew',                          artist: 'Miles Davis'                  },
      { album: 'The Kinks Are the Village Green Preservation Society', artist: 'The Kinks'     },
      { album: 'Stand!',                                artist: 'Sly and the Family Stone'     },
      { album: 'At Folsom Prison',                      artist: 'Johnny Cash'                  },
      { album: 'At San Quentin',                        artist: 'Johnny Cash'                  },
      { album: 'Music from Big Pink',                   artist: 'The Band'                     },
      { album: 'The Band',                              artist: 'The Band'                     },
      { album: 'Dusty in Memphis',                      artist: 'Dusty Springfield'            },
      { album: 'Disraeli Gears',                        artist: 'Cream'                        },
      { album: 'Wheels of Fire',                        artist: 'Cream'                        },
      { album: 'Surrealistic Pillow',                   artist: 'Jefferson Airplane'           },
      { album: 'Odessey and Oracle',                    artist: 'The Zombies'                  },
      { album: 'Santana',                               artist: 'Santana'                      },
      { album: 'Hot Rats',                              artist: 'Frank Zappa'                  },
      { album: 'Where Did Our Love Go',                 artist: 'The Supremes'                 },
      { album: 'Live at the Apollo',                    artist: 'James Brown'                  },
    ],
  },
  {
    label: '1970s',
    albums: [
      { album: 'The Dark Side of the Moon',                              artist: 'Pink Floyd'         },
      { album: 'Wish You Were Here',                                     artist: 'Pink Floyd'         },
      { album: 'The Wall',                                               artist: 'Pink Floyd'         },
      { album: 'Led Zeppelin IV',                                        artist: 'Led Zeppelin'       },
      { album: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', artist: 'David Bowie' },
      { album: 'Heroes',                                                 artist: 'David Bowie'        },
      { album: 'Rumours',                                                artist: 'Fleetwood Mac'      },
      { album: 'Songs in the Key of Life',                               artist: 'Stevie Wonder'      },
      { album: 'Innervisions',                                           artist: 'Stevie Wonder'      },
      { album: "What's Going On",                                        artist: 'Marvin Gaye'        },
      { album: 'Born to Run',                                            artist: 'Bruce Springsteen'  },
      { album: 'Darkness on the Edge of Town',                           artist: 'Bruce Springsteen'  },
      { album: 'Hotel California',                                       artist: 'Eagles'             },
      { album: 'Their Greatest Hits',                                    artist: 'Eagles'             },
      { album: 'London Calling',                                         artist: 'The Clash'          },
      { album: 'Never Mind the Bollocks',                                artist: 'Sex Pistols'        },
      { album: 'Ramones',                                                artist: 'Ramones'            },
      { album: 'Paranoid',                                               artist: 'Black Sabbath'      },
      { album: 'Master of Reality',                                      artist: 'Black Sabbath'      },
      { album: 'Highway to Hell',                                        artist: 'AC/DC'              },
      { album: 'Back in Black',                                          artist: 'AC/DC'              },
      { album: 'A Night at the Opera',                                   artist: 'Queen'              },
      { album: 'News of the World',                                      artist: 'Queen'              },
      { album: 'Goodbye Yellow Brick Road',                              artist: 'Elton John'         },
      { album: 'Honky Château',                                          artist: 'Elton John'         },
      { album: 'Blue',                                                   artist: 'Joni Mitchell'      },
      { album: 'Harvest',                                                artist: 'Neil Young'         },
      { album: 'Exodus',                                                 artist: 'Bob Marley'         },
      { album: 'Rastaman Vibration',                                     artist: 'Bob Marley'         },
      { album: 'Autobahn',                                               artist: 'Kraftwerk'          },
      { album: 'The Man-Machine',                                        artist: 'Kraftwerk'          },
      { album: 'Bad Girls',                                              artist: 'Donna Summer'       },
      { album: 'Saturday Night Fever',                                   artist: 'Bee Gees'           },
      { album: 'Fear of Music',                                          artist: 'Talking Heads'      },
      { album: 'More Songs About Buildings and Food',                    artist: 'Talking Heads'      },
      { album: 'Marquee Moon',                                           artist: 'Television'         },
      { album: 'Horses',                                                 artist: 'Patti Smith'        },
      { album: 'Exile on Main St.',                                      artist: 'The Rolling Stones' },
      { album: 'Transformer',                                            artist: 'Lou Reed'           },
      { album: 'Van Halen',                                              artist: 'Van Halen'          },
      { album: 'Breakfast in America',                                   artist: 'Supertramp'         },
      { album: "Who's Next",                                             artist: 'The Who'            },
      { album: 'Mothership Connection',                                  artist: 'Parliament'         },
      { album: 'Super Fly',                                              artist: 'Curtis Mayfield'    },
      { album: "Let's Stay Together",                                    artist: 'Al Green'           },
      { album: 'Unknown Pleasures',                                      artist: 'Joy Division'       },
      { album: 'Off the Wall',                                           artist: 'Michael Jackson'    },
      { album: "All 'N All",                                             artist: 'Earth, Wind & Fire' },
    ],
  },
  {
    label: '1980s',
    albums: [
      { album: 'Thriller',                                  artist: 'Michael Jackson'  },
      { album: 'Bad',                                       artist: 'Michael Jackson'  },
      { album: 'Purple Rain',                               artist: 'Prince'           },
      { album: 'Sign o\' the Times',                        artist: 'Prince'           },
      { album: 'Like a Prayer',                             artist: 'Madonna'          },
      { album: 'True Blue',                                 artist: 'Madonna'          },
      { album: 'The Joshua Tree',                           artist: 'U2'               },
      { album: 'Achtung Baby',                              artist: 'U2'               },
      { album: 'Born in the U.S.A.',                        artist: 'Bruce Springsteen'},
      { album: 'Appetite for Destruction',                  artist: "Guns N' Roses"    },
      { album: 'Master of Puppets',                         artist: 'Metallica'        },
      { album: 'Ride the Lightning',                        artist: 'Metallica'        },
      { album: 'Reign in Blood',                            artist: 'Slayer'           },
      { album: 'The Number of the Beast',                   artist: 'Iron Maiden'      },
      { album: 'The Queen Is Dead',                         artist: 'The Smiths'       },
      { album: 'Disintegration',                            artist: 'The Cure'         },
      { album: 'Closer',                                    artist: 'Joy Division'     },
      { album: 'Power, Corruption & Lies',                  artist: 'New Order'        },
      { album: 'Violator',                                  artist: 'Depeche Mode'     },
      { album: 'Remain in Light',                           artist: 'Talking Heads'    },
      { album: 'Speaking in Tongues',                       artist: 'Talking Heads'    },
      { album: 'Murmur',                                    artist: 'R.E.M.'           },
      { album: 'Document',                                  artist: 'R.E.M.'           },
      { album: 'Whitney Houston',                           artist: 'Whitney Houston'  },
      { album: 'Control',                                   artist: 'Janet Jackson'    },
      { album: 'Rhythm Nation 1814',                        artist: 'Janet Jackson'    },
      { album: 'It Takes a Nation of Millions to Hold Us Back', artist: 'Public Enemy' },
      { album: 'Straight Outta Compton',                    artist: 'N.W.A'            },
      { album: 'Licensed to Ill',                           artist: 'Beastie Boys'     },
      { album: 'Raising Hell',                              artist: 'Run-D.M.C.'       },
      { album: 'Daydream Nation',                           artist: 'Sonic Youth'      },
      { album: 'Doolittle',                                 artist: 'Pixies'           },
      { album: 'The Stone Roses',                           artist: 'The Stone Roses'  },
      { album: 'Kick',                                      artist: 'INXS'             },
      { album: 'Faith',                                     artist: 'George Michael'   },
      { album: 'Hounds of Love',                            artist: 'Kate Bush'        },
      { album: 'Songs from the Big Chair',                  artist: 'Tears for Fears'  },
      { album: 'No Jacket Required',                        artist: 'Phil Collins'     },
      { album: 'Actually',                                  artist: 'Pet Shop Boys'    },
      { album: "She's So Unusual",                          artist: 'Cyndi Lauper'     },
      { album: 'Slippery When Wet',                         artist: 'Bon Jovi'         },
      { album: 'Hysteria',                                  artist: 'Def Leppard'      },
      { album: '1984',                                      artist: 'Van Halen'        },
      { album: 'Stop Making Sense',                         artist: 'Talking Heads'    },
      { album: 'Synchronicity',                             artist: 'The Police'       },
      { album: 'Back in Black',                             artist: 'AC/DC'            },
      { album: 'Paid in Full',                              artist: 'Eric B. & Rakim'  },
      { album: 'Diamond Life',                              artist: 'Sade'             },
    ],
  },
  {
    label: '1990s',
    albums: [
      { album: 'Nevermind',                        artist: 'Nirvana'                  },
      { album: 'OK Computer',                      artist: 'Radiohead'                },
      { album: "(What's the Story) Morning Glory?",artist: 'Oasis'                    },
      { album: 'Parklife',                         artist: 'Blur'                     },
      { album: 'Ten',                              artist: 'Pearl Jam'                },
      { album: 'Superunknown',                     artist: 'Soundgarden'              },
      { album: 'Dirt',                             artist: 'Alice in Chains'          },
      { album: 'Blood Sugar Sex Magik',            artist: 'Red Hot Chili Peppers'    },
      { album: 'Dookie',                           artist: 'Green Day'                },
      { album: 'Weezer',                           artist: 'Weezer'                   },
      { album: 'The Miseducation of Lauryn Hill',  artist: 'Lauryn Hill'              },
      { album: 'Illmatic',                         artist: 'Nas'                      },
      { album: 'The Chronic',                      artist: 'Dr. Dre'                  },
      { album: 'All Eyez on Me',                   artist: 'Tupac'                    },
      { album: 'Ready to Die',                     artist: 'The Notorious B.I.G.'     },
      { album: 'Enter the Wu-Tang (36 Chambers)',  artist: 'Wu-Tang Clan'             },
      { album: 'Aquemini',                         artist: 'OutKast'                  },
      { album: 'The Low End Theory',               artist: 'A Tribe Called Quest'     },
      { album: 'Rage Against the Machine',         artist: 'Rage Against the Machine' },
      { album: 'Mezzanine',                        artist: 'Massive Attack'           },
      { album: 'Dummy',                            artist: 'Portishead'               },
      { album: 'Homogenic',                        artist: 'Björk'                    },
      { album: 'Post',                             artist: 'Björk'                    },
      { album: 'Richard D. James Album',           artist: 'Aphex Twin'               },
      { album: 'Homework',                         artist: 'Daft Punk'                },
      { album: 'The Fat of the Land',              artist: 'The Prodigy'              },
      { album: 'Loveless',                         artist: 'My Bloody Valentine'      },
      { album: 'Slanted and Enchanted',            artist: 'Pavement'                 },
      { album: 'Either/Or',                        artist: 'Elliott Smith'            },
      { album: 'Grace',                            artist: 'Jeff Buckley'             },
      { album: 'Tidal',                            artist: 'Fiona Apple'              },
      { album: 'Siamese Dream',                    artist: 'Smashing Pumpkins'        },
      { album: 'Ænima',                            artist: 'Tool'                     },
      { album: 'Follow the Leader',                artist: 'Korn'                     },
      { album: 'Around the Fur',                   artist: 'Deftones'                 },
      { album: 'The Downward Spiral',              artist: 'Nine Inch Nails'          },
      { album: 'Doggystyle',                       artist: 'Snoop Dogg'               },
      { album: 'Reasonable Doubt',                 artist: 'Jay-Z'                    },
      { album: 'Supa Dupa Fly',                    artist: 'Missy Elliott'            },
      { album: 'CrazySexyCool',                    artist: 'TLC'                      },
      { album: 'Jagged Little Pill',               artist: 'Alanis Morissette'        },
      { album: '...Baby One More Time',            artist: 'Britney Spears'           },
      { album: 'Millennium',                       artist: 'Backstreet Boys'          },
      { album: 'The Slim Shady LP',                artist: 'Eminem'                   },
      { album: 'Odelay',                           artist: 'Beck'                     },
      { album: 'The Lonesome Crowded West',        artist: 'Modest Mouse'             },
      { album: 'In the Aeroplane Over the Sea',    artist: 'Neutral Milk Hotel'       },
      { album: 'Buena Vista Social Club',          artist: 'Buena Vista Social Club'  },
    ],
  },
  {
    label: '2000s',
    albums: [
      { album: 'The College Dropout',                            artist: 'Kanye West'           },
      { album: 'Graduation',                                     artist: 'Kanye West'           },
      { album: 'The Marshall Mathers LP',                        artist: 'Eminem'               },
      { album: 'The Blueprint',                                  artist: 'Jay-Z'                },
      { album: 'Stankonia',                                      artist: 'OutKast'              },
      { album: 'Madvillainy',                                    artist: 'MF DOOM'              },
      { album: 'Get Rich or Die Tryin\'',                        artist: '50 Cent'              },
      { album: 'Tha Carter III',                                 artist: 'Lil Wayne'            },
      { album: 'Kid A',                                          artist: 'Radiohead'            },
      { album: 'In Rainbows',                                    artist: 'Radiohead'            },
      { album: "Whatever People Say I Am, That's What I'm Not", artist: 'Arctic Monkeys'       },
      { album: 'Is This It',                                     artist: 'The Strokes'          },
      { album: 'Turn on the Bright Lights',                      artist: 'Interpol'             },
      { album: 'Elephant',                                       artist: 'The White Stripes'    },
      { album: 'Franz Ferdinand',                                artist: 'Franz Ferdinand'      },
      { album: 'A Rush of Blood to the Head',                    artist: 'Coldplay'             },
      { album: 'Viva la Vida',                                   artist: 'Coldplay'             },
      { album: 'Back to Black',                                  artist: 'Amy Winehouse'        },
      { album: "B'Day",                                          artist: 'Beyoncé'              },
      { album: 'I Am… Sasha Fierce',                             artist: 'Beyoncé'              },
      { album: 'FutureSex/LoveSounds',                           artist: 'Justin Timberlake'    },
      { album: 'Good Girl Gone Bad',                             artist: 'Rihanna'              },
      { album: 'The Fame',                                       artist: 'Lady Gaga'            },
      { album: 'Blackout',                                       artist: 'Britney Spears'       },
      { album: 'Discovery',                                      artist: 'Daft Punk'            },
      { album: 'Hot Fuss',                                       artist: 'The Killers'          },
      { album: 'Funeral',                                        artist: 'Arcade Fire'          },
      { album: 'Illinois',                                       artist: 'Sufjan Stevens'       },
      { album: 'For Emma, Forever Ago',                          artist: 'Bon Iver'             },
      { album: 'Fleet Foxes',                                    artist: 'Fleet Foxes'          },
      { album: 'Sound of Silver',                                artist: 'LCD Soundsystem'      },
      { album: 'Merriweather Post Pavilion',                     artist: 'Animal Collective'    },
      { album: 'Demon Days',                                     artist: 'Gorillaz'             },
      { album: 'Hybrid Theory',                                  artist: 'Linkin Park'          },
      { album: 'Toxicity',                                       artist: 'System of a Down'     },
      { album: 'American Idiot',                                 artist: 'Green Day'            },
      { album: 'The Black Parade',                               artist: 'My Chemical Romance'  },
      { album: 'Riot!',                                          artist: 'Paramore'             },
      { album: 'Blink-182',                                      artist: 'Blink-182'            },
      { album: 'From Under the Cork Tree',                       artist: 'Fall Out Boy'         },
      { album: 'xx',                                             artist: 'The xx'               },
      { album: 'Ys',                                             artist: 'Joanna Newsom'        },
      { album: 'Untrue',                                         artist: 'Burial'               },
      { album: 'Kala',                                           artist: 'M.I.A.'               },
      { album: 'Vampire Weekend',                                artist: 'Vampire Weekend'      },
      { album: 'Wolfgang Amadeus Phoenix',                       artist: 'Phoenix'              },
      { album: 'Cross',                                          artist: 'Justice'              },
      { album: 'Songs in A Minor',                               artist: 'Alicia Keys'          },
    ],
  },
  {
    label: '2010s',
    albums: [
      { album: 'To Pimp a Butterfly',               artist: 'Kendrick Lamar'     },
      { album: 'good kid, m.A.A.d city',            artist: 'Kendrick Lamar'     },
      { album: 'My Beautiful Dark Twisted Fantasy', artist: 'Kanye West'         },
      { album: 'Take Care',                         artist: 'Drake'              },
      { album: 'Astroworld',                        artist: 'Travis Scott'       },
      { album: 'DS2',                               artist: 'Future'             },
      { album: 'Igor',                              artist: 'Tyler, The Creator' },
      { album: 'Blonde',                            artist: 'Frank Ocean'        },
      { album: 'channel ORANGE',                    artist: 'Frank Ocean'        },
      { album: 'Lemonade',                          artist: 'Beyoncé'            },
      { album: 'Beyoncé',                           artist: 'Beyoncé'            },
      { album: '1989',                              artist: 'Taylor Swift'       },
      { album: 'Red',                               artist: 'Taylor Swift'       },
      { album: 'Thank U, Next',                     artist: 'Ariana Grande'      },
      { album: 'When We All Fall Asleep, Where Do We Go?', artist: 'Billie Eilish' },
      { album: 'Melodrama',                         artist: 'Lorde'              },
      { album: 'Norman Fucking Rockwell!',          artist: 'Lana Del Rey'       },
      { album: 'House of Balloons',                 artist: 'The Weeknd'         },
      { album: 'Beauty Behind the Madness',         artist: 'The Weeknd'         },
      { album: 'Ctrl',                              artist: 'SZA'                },
      { album: 'Anti',                              artist: 'Rihanna'            },
      { album: 'A Seat at the Table',               artist: 'Solange'            },
      { album: 'Currents',                          artist: 'Tame Impala'        },
      { album: 'Lonerism',                          artist: 'Tame Impala'        },
      { album: 'AM',                                artist: 'Arctic Monkeys'     },
      { album: '?',                                 artist: 'XXXTENTACION'       },
      { album: 'Bon Iver',                          artist: 'Bon Iver'           },
      { album: 'Carrie & Lowell',                   artist: 'Sufjan Stevens'     },
      { album: 'Stranger in the Alps',              artist: 'Phoebe Bridgers'    },
      { album: 'Modern Vampires of the City',       artist: 'Vampire Weekend'    },
      { album: 'This Is Happening',                 artist: 'LCD Soundsystem'    },
      { album: 'Random Access Memories',            artist: 'Daft Punk'          },
      { album: 'Pop 2',                             artist: 'Charli XCX'         },
      { album: 'Emotion',                           artist: 'Carly Rae Jepsen'   },
      { album: 'Flower Boy',                        artist: 'Tyler, The Creator' },
      { album: 'Die Lit',                           artist: 'Playboi Carti'      },
      { album: 'Barter 6',                          artist: 'Young Thug'         },
      { album: 'At.Long.Last.A$AP',                 artist: 'A$AP Rocky'         },
      { album: '2014 Forest Hills Drive',           artist: 'J. Cole'            },
      { album: 'Swimming',                          artist: 'Mac Miller'         },
      { album: 'Acid Rap',                          artist: 'Chance the Rapper'  },
      { album: 'Awaken, My Love!',                  artist: 'Childish Gambino'   },
      { album: 'LP1',                               artist: 'FKA twigs'          },
      { album: 'Bloom',                             artist: 'Beach House'        },
      { album: 'Art Angels',                        artist: 'Grimes'             },
      { album: 'The Money Store',                   artist: 'Death Grips'        },
      { album: 'Saturation',                        artist: 'Brockhampton'       },
      { album: 'Be the Cowboy',                     artist: 'Mitski'             },
    ],
  },
  {
    label: '2020s',
    albums: [
      { album: 'Midnights',                                              artist: 'Taylor Swift'         },
      { album: 'The Tortured Poets Department',                          artist: 'Taylor Swift'         },
      { album: 'Sour',                                                   artist: 'Olivia Rodrigo'       },
      { album: 'Guts',                                                   artist: 'Olivia Rodrigo'       },
      { album: 'Hit Me Hard and Soft',                                   artist: 'Billie Eilish'        },
      { album: 'SOS',                                                    artist: 'SZA'                  },
      { album: 'Short n\' Sweet',                                        artist: 'Sabrina Carpenter'    },
      { album: 'BRAT',                                                   artist: 'Charli XCX'           },
      { album: 'Cowboy Carter',                                          artist: 'Beyoncé'              },
      { album: 'Renaissance',                                            artist: 'Beyoncé'              },
      { album: 'After Hours',                                            artist: 'The Weeknd'           },
      { album: 'Future Nostalgia',                                       artist: 'Dua Lipa'             },
      { album: 'Eternal Sunshine',                                       artist: 'Ariana Grande'        },
      { album: 'Un Verano Sin Ti',                                       artist: 'Bad Bunny'            },
      { album: 'Nadie Sabe Lo Que Va a Pasar Mañana',                   artist: 'Bad Bunny'            },
      { album: 'Utopia',                                                 artist: 'Travis Scott'         },
      { album: 'For All the Dogs',                                       artist: 'Drake'                },
      { album: 'Heroes & Villains',                                      artist: 'Metro Boomin'         },
      { album: 'We Don\'t Trust You',                                    artist: 'Future & Metro Boomin'},
      { album: 'Call Me If You Get Lost',                                artist: 'Tyler, The Creator'   },
      { album: 'Whole Lotta Red',                                        artist: 'Playboi Carti'        },
      { album: 'Mr. Morale & the Big Steppers',                          artist: 'Kendrick Lamar'       },
      { album: 'The Off-Season',                                         artist: 'J. Cole'              },
      { album: 'A Gift & a Curse',                                       artist: 'Gunna'                },
      { album: 'Actual Life 3',                                          artist: 'Fred again..'         },
      { album: 'Quest for Fire',                                         artist: 'Skrillex'             },
      { album: 'Did You Know That There\'s a Tunnel Under Ocean Blvd',   artist: 'Lana Del Rey'         },
      { album: 'The Record',                                             artist: 'Boygenius'            },
      { album: 'The Land Is Inhospitable and So Are We',                 artist: 'Mitski'               },
      { album: 'Dragon New Warm Mountain I Believe in You',              artist: 'Big Thief'            },
      { album: 'Punisher',                                               artist: 'Phoebe Bridgers'      },
      { album: 'Stick Season',                                           artist: 'Noah Kahan'           },
      { album: 'Zach Bryan',                                             artist: 'Zach Bryan'           },
      { album: 'One Thing at a Time',                                    artist: 'Morgan Wallen'        },
      { album: 'I Told Them…',                                           artist: 'Burna Boy'            },
      { album: 'Rave & Roses',                                           artist: 'Rema'                 },
      { album: 'Work of Art',                                            artist: 'Asake'                },
      { album: 'Born in the Wild',                                       artist: 'Tems'                 },
      { album: 'Mañana Será Bonito',                                     artist: 'Karol G'              },
      { album: 'Ferxxocalipsis',                                         artist: 'Feid'                 },
      { album: 'Saturno',                                                artist: 'Rauw Alejandro'       },
      { album: 'Motomami',                                               artist: 'Rosalía'              },
      { album: 'Like..?',                                                artist: 'Ice Spice'            },
      { album: "Let's Start Here",                                       artist: 'Lil Yachty'           },
      { album: 'Desire, I Want to Turn Into You',                        artist: 'Caroline Polachek'    },
      { album: 'Lahai',                                                  artist: 'Sampha'               },
      { album: 'Underdressed at the Symphony',                           artist: 'Faye Webster'         },
      { album: 'Bright Future',                                          artist: 'Adrianne Lenker'      },
    ],
  },
];

module.exports = { PLACEHOLDER_ARTISTS, GENRES, DECADES };
