// Curated album/artist lists that drive the cron refresh.
// These mirror the hardcoded data that was previously in the React Native app.

const PLACEHOLDER_ARTISTS = [
  { name: 'Kendrick Lamar',    genre: 'Rap'       },
  { name: 'Taylor Swift',      genre: 'Pop'       },
  { name: 'SZA',               genre: 'R&B'       },
  { name: 'Tyler the Creator', genre: 'Rap'       },
  { name: 'Billie Eilish',     genre: 'Pop'       },
  { name: 'Bad Bunny',         genre: 'Reggaeton' },
  { name: 'The Weeknd',        genre: 'R&B'       },
  { name: 'Chappell Roan',     genre: 'Pop'       },
];

const GENRES = [
  {
    label: 'Rap',
    albums: [
      { album: 'DAMN.',                             artist: 'Kendrick Lamar'  },
      { album: 'Take Care',                         artist: 'Drake'           },
      { album: 'To Pimp a Butterfly',               artist: 'Kendrick Lamar'  },
      { album: 'ASTROWORLD',                        artist: 'Travis Scott'    },
      { album: '2014 Forest Hills Drive',           artist: 'J. Cole'         },
      { album: 'My Beautiful Dark Twisted Fantasy', artist: 'Kanye West'      },
      { album: 'The Blueprint',                     artist: 'JAY-Z'           },
      { album: 'Illmatic',                          artist: 'Nas'             },
      { album: 'good kid, m.A.A.d city',            artist: 'Kendrick Lamar'  },
      { album: 'The Marshall Mathers LP',           artist: 'Eminem'          },
    ],
  },
  {
    label: 'R&B',
    albums: [
      { album: 'After Hours',       artist: 'The Weeknd'    },
      { album: 'SOS',               artist: 'SZA'           },
      { album: 'Lemonade',          artist: 'Beyoncé'       },
      { album: 'channel ORANGE',    artist: 'Frank Ocean'   },
      { album: 'Freudian',          artist: 'Daniel Caesar' },
      { album: 'WASTELAND',         artist: 'Brent Faiyaz'  },
      { album: 'Still Over It',     artist: 'Summer Walker' },
      { album: 'Starboy',           artist: 'The Weeknd'    },
      { album: 'American Teen',     artist: 'Khalid'        },
      { album: 'Back of My Mind',   artist: 'H.E.R.'        },
    ],
  },
  {
    label: 'Pop',
    albums: [
      { album: 'folklore',                              artist: 'Taylor Swift'  },
      { album: 'Midnights',                             artist: 'Taylor Swift'  },
      { album: '30',                                    artist: 'Adele'         },
      { album: 'Future Nostalgia',                      artist: 'Dua Lipa'      },
      { album: "Harry's House",                         artist: 'Harry Styles'  },
      { album: 'SOUR',                                  artist: 'Olivia Rodrigo'},
      { album: 'When We All Fall Asleep Where Do We Go',artist: 'Billie Eilish' },
      { album: 'Divide',                                artist: 'Ed Sheeran'    },
      { album: 'thank u, next',                         artist: 'Ariana Grande' },
      { album: "Hollywood's Bleeding",                  artist: 'Post Malone'   },
    ],
  },
  {
    label: 'Rock',
    albums: [
      { album: 'AM',                artist: 'Arctic Monkeys'          },
      { album: 'OK Computer',       artist: 'Radiohead'               },
      { album: 'Is This It',        artist: 'The Strokes'             },
      { album: 'Currents',          artist: 'Tame Impala'             },
      { album: 'El Camino',         artist: 'The Black Keys'          },
      { album: 'Wasting Light',     artist: 'Foo Fighters'            },
      { album: 'Stadium Arcadium',  artist: 'Red Hot Chili Peppers'   },
      { album: '...Like Clockwork', artist: 'Queens of the Stone Age' },
      { album: 'Origin of Symmetry',artist: 'Muse'                    },
      { album: "Whatever People Say I Am, That's What I'm Not", artist: 'Arctic Monkeys' },
    ],
  },
  {
    label: 'House',
    albums: [
      { album: 'Random Access Memories', artist: 'Daft Punk'    },
      { album: 'Discovery',              artist: 'Daft Punk'    },
      { album: 'Settle',                 artist: 'Disclosure'   },
      { album: 'Caracal',                artist: 'Disclosure'   },
      { album: 'In Colour',              artist: 'Jamie xx'     },
      { album: 'There Is Love In You',   artist: 'Four Tet'     },
      { album: 'Swim',                   artist: 'Caribou'      },
      { album: 'Motion',                 artist: 'Calvin Harris' },
      { album: 'Actual Life 3',          artist: 'Fred again..' },
      { album: 'Black Sands',            artist: 'Bonobo'       },
    ],
  },
  {
    label: 'Jazz',
    albums: [
      { album: 'Kind of Blue',        artist: 'Miles Davis'          },
      { album: 'A Love Supreme',      artist: 'John Coltrane'        },
      { album: 'Time Out',            artist: 'Dave Brubeck Quartet' },
      { album: 'Head Hunters',        artist: 'Herbie Hancock'       },
      { album: 'Waltz for Debby',     artist: 'Bill Evans'           },
      { album: 'Mingus Ah Um',        artist: 'Charles Mingus'       },
      { album: 'Chet Baker Sings',    artist: 'Chet Baker'           },
      { album: 'Saxophone Colossus',  artist: 'Sonny Rollins'        },
      { album: 'Sketches of Spain',   artist: 'Miles Davis'          },
      { album: "Monk's Dream",        artist: 'Thelonious Monk'      },
    ],
  },
  {
    label: 'Soul',
    albums: [
      { album: "What's Going On",                 artist: 'Marvin Gaye'    },
      { album: 'Back to Black',                   artist: 'Amy Winehouse'  },
      { album: 'The Miseducation of Lauryn Hill',  artist: 'Ms. Lauryn Hill'},
      { album: 'Songs in the Key of Life',         artist: 'Stevie Wonder'  },
      { album: 'Voodoo',                           artist: "D'Angelo"       },
      { album: 'A Seat at the Table',              artist: 'Solange'        },
      { album: 'Baduizm',                          artist: 'Erykah Badu'   },
      { album: 'Get Lifted',                       artist: 'John Legend'    },
      { album: 'Songs in A Minor',                 artist: 'Alicia Keys'    },
      { album: 'Coming Home',                      artist: 'Leon Bridges'   },
    ],
  },
  {
    label: 'Country',
    albums: [
      { album: 'Dangerous: The Double Album',        artist: 'Morgan Wallen'    },
      { album: 'Golden Hour',                        artist: 'Kacey Musgraves'  },
      { album: 'Traveller',                          artist: 'Chris Stapleton'  },
      { album: 'American Heartbreak',                artist: 'Zach Bryan'       },
      { album: "This One's for You",                 artist: 'Luke Combs'       },
      { album: 'Purgatory',                          artist: 'Tyler Childers'   },
      { album: 'Metamodern Sounds in Country Music', artist: 'Sturgill Simpson' },
      { album: 'By the Way, I Forgive You',          artist: 'Brandi Carlile'   },
      { album: 'Southeastern',                       artist: 'Jason Isbell'     },
      { album: 'Stoned Side of the Mtn',             artist: 'Tyler Childers'   },
    ],
  },
];

const DECADES = [
  {
    label: '1950s',
    albums: [
      { album: "Songs for Swingin' Lovers!",              artist: 'Frank Sinatra'        },
      { album: 'Kind of Blue',                            artist: 'Miles Davis'          },
      { album: 'Time Out',                                artist: 'Dave Brubeck Quartet' },
      { album: 'Elvis Presley',                           artist: 'Elvis Presley'        },
      { album: 'Come Fly with Me',                        artist: 'Frank Sinatra'        },
      { album: "Moanin'",                                 artist: 'Art Blakey'           },
      { album: 'The Genius of Ray Charles',               artist: 'Ray Charles'          },
      { album: 'Ella and Louis',                          artist: 'Ella Fitzgerald'      },
      { album: 'Johnny Cash with His Hot and Blue Guitar',artist: 'Johnny Cash'          },
      { album: 'Mingus Ah Um',                            artist: 'Charles Mingus'       },
    ],
  },
  {
    label: '1960s',
    albums: [
      { album: 'Revolver',                              artist: 'The Beatles'           },
      { album: 'Pet Sounds',                            artist: 'The Beach Boys'        },
      { album: 'Highway 61 Revisited',                  artist: 'Bob Dylan'             },
      { album: "Sgt. Pepper's Lonely Hearts Club Band", artist: 'The Beatles'           },
      { album: 'The Velvet Underground & Nico',         artist: 'The Velvet Underground'},
      { album: 'Blonde on Blonde',                      artist: 'Bob Dylan'             },
      { album: 'Abbey Road',                            artist: 'The Beatles'           },
      { album: 'Are You Experienced',                   artist: 'Jimi Hendrix'          },
      { album: 'Led Zeppelin',                          artist: 'Led Zeppelin'          },
      { album: 'Aftermath',                             artist: 'The Rolling Stones'    },
    ],
  },
  {
    label: '1970s',
    albums: [
      { album: 'The Dark Side of the Moon', artist: 'Pink Floyd'         },
      { album: 'Rumours',                   artist: 'Fleetwood Mac'      },
      { album: 'Led Zeppelin IV',           artist: 'Led Zeppelin'       },
      { album: 'Born to Run',               artist: 'Bruce Springsteen'  },
      { album: 'Tapestry',                  artist: 'Carole King'        },
      { album: 'Hotel California',          artist: 'Eagles'             },
      { album: 'Exile on Main St.',         artist: 'The Rolling Stones' },
      { album: 'Innervisions',              artist: 'Stevie Wonder'      },
      { album: 'London Calling',            artist: 'The Clash'          },
      { album: 'Off the Wall',              artist: 'Michael Jackson'    },
    ],
  },
  {
    label: '1980s',
    albums: [
      { album: 'Thriller',                 artist: 'Michael Jackson'  },
      { album: 'Purple Rain',              artist: 'Prince'           },
      { album: 'The Joshua Tree',          artist: 'U2'               },
      { album: 'Appetite for Destruction', artist: "Guns N' Roses"    },
      { album: 'Back in Black',            artist: 'AC/DC'            },
      { album: 'Born in the U.S.A.',       artist: 'Bruce Springsteen'},
      { album: "Sign 'O' the Times",       artist: 'Prince'           },
      { album: 'Graceland',                artist: 'Paul Simon'       },
      { album: 'Like a Prayer',            artist: 'Madonna'          },
      { album: 'Eliminator',               artist: 'ZZ Top'           },
    ],
  },
  {
    label: '1990s',
    albums: [
      { album: 'Nevermind',                        artist: 'Nirvana'                  },
      { album: 'The Chronic',                      artist: 'Dr. Dre'                  },
      { album: 'OK Computer',                      artist: 'Radiohead'                },
      { album: 'Illmatic',                         artist: 'Nas'                      },
      { album: 'Ten',                              artist: 'Pearl Jam'                },
      { album: 'Ready to Die',                     artist: 'The Notorious B.I.G.'     },
      { album: 'Jagged Little Pill',               artist: 'Alanis Morissette'        },
      { album: 'Achtung Baby',                     artist: 'U2'                       },
      { album: 'The Miseducation of Lauryn Hill',  artist: 'Ms. Lauryn Hill'          },
      { album: 'Reasonable Doubt',                 artist: 'JAY-Z'                    },
    ],
  },
  {
    label: '2000s',
    albums: [
      { album: 'The College Dropout',                               artist: 'Kanye West'           },
      { album: 'Is This It',                                        artist: 'The Strokes'          },
      { album: 'Speakerboxxx/The Love Below',                       artist: 'Outkast'              },
      { album: 'Funeral',                                           artist: 'Arcade Fire'          },
      { album: 'Elephant',                                          artist: 'The White Stripes'    },
      { album: 'American Idiot',                                    artist: 'Green Day'            },
      { album: 'Late Registration',                                 artist: 'Kanye West'           },
      { album: 'Stankonia',                                         artist: 'Outkast'              },
      { album: "Whatever People Say I Am, That's What I'm Not",    artist: 'Arctic Monkeys'       },
      { album: 'Stadium Arcadium',                                  artist: 'Red Hot Chili Peppers'},
    ],
  },
  {
    label: '2010s',
    albums: [
      { album: 'To Pimp a Butterfly',               artist: 'Kendrick Lamar'  },
      { album: 'Blonde',                            artist: 'Frank Ocean'     },
      { album: 'My Beautiful Dark Twisted Fantasy', artist: 'Kanye West'      },
      { album: 'good kid, m.A.A.d city',            artist: 'Kendrick Lamar'  },
      { album: 'Lemonade',                          artist: 'Beyoncé'         },
      { album: '1989',                              artist: 'Taylor Swift'    },
      { album: 'AM',                                artist: 'Arctic Monkeys'  },
      { album: 'Currents',                          artist: 'Tame Impala'     },
      { album: 'Random Access Memories',            artist: 'Daft Punk'       },
      { album: 'channel ORANGE',                    artist: 'Frank Ocean'     },
    ],
  },
  {
    label: '2020s',
    albums: [
      { album: 'folklore',                      artist: 'Taylor Swift'   },
      { album: 'After Hours',                   artist: 'The Weeknd'     },
      { album: 'Mr. Morale & the Big Steppers', artist: 'Kendrick Lamar' },
      { album: 'SOS',                           artist: 'SZA'            },
      { album: 'Un Verano Sin Ti',              artist: 'Bad Bunny'      },
      { album: 'Future Nostalgia',              artist: 'Dua Lipa'       },
      { album: 'SOUR',                          artist: 'Olivia Rodrigo' },
      { album: 'Midnights',                     artist: 'Taylor Swift'   },
      { album: "Harry's House",                 artist: 'Harry Styles'   },
      { album: 'Actual Life 3',                 artist: 'Fred again..'   },
    ],
  },
];

module.exports = { PLACEHOLDER_ARTISTS, GENRES, DECADES };
